### ISSUE TITLE
libtorrent session destructor hang

### ISSUE THREAD

**Issue by aresch** [arvidn/libtorrent#1199]
libtorrent version (or branch): 1_1_RC
platform/architecture: linux
compiler and compiler version: gcc 6.2.1
built with no deprecated functions

libtorrent session destructor hangs when shutting down right after adding a torrent to the session.

Run this python script and it will hang:
```
import libtorrent as lt

s = lt.session({})
atp = {}
atp['ti'] = lt.torrent_info(lt.bdecode(open('test.torrent', 'rb').read()))
atp['save_path'] = '/tmp'

s.add_torrent(atp)
```

The torrent file is pretty sparse on metadata and looks like this (pieces snipped).

```
{b'announce': b'', b'info': {b'piece length': 16384, b'name': b'/tmp/randomfile', b'length': 4194304, b'pieces': '...'}
```

I attached gdb while it was hanging and got the thread stacks:
```
Thread 3 (Thread 0x7f7ad0bbd700 (LWP 3387)):
#0  0x00007f7ad669d10f in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00007f7ad4fe0822 in boost::asio::detail::posix_thread::func<boost::asio::detail::resolver_service_base::work_io_service_runner>::run() ()
   from /usr/lib/libtorrent-rasterbar.so.9
#2  0x00007f7ad4fc0e1f in ?? () from /usr/lib/libtorrent-rasterbar.so.9
#3  0x00007f7ad6697454 in start_thread () from /usr/lib/libpthread.so.0
#4  0x00007f7ad63da7df in clone () from /usr/lib/libc.so.6

Thread 2 (Thread 0x7f7ad33c2700 (LWP 3382)):
#0  0x00007f7ad63dadd3 in epoll_wait () from /usr/lib/libc.so.6
#1  0x00007f7ad4fdebff in ?? () from /usr/lib/libtorrent-rasterbar.so.9
#2  0x00007f7ad50a873f in ?? () from /usr/lib/libtorrent-rasterbar.so.9
#3  0x00007f7ad4fc0e1f in ?? () from /usr/lib/libtorrent-rasterbar.so.9
#4  0x00007f7ad6697454 in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007f7ad63da7df in clone () from /usr/lib/libc.so.6

Thread 1 (Thread 0x7f7ad6f60400 (LWP 3381)):
#0  0x00007f7ad669868d in pthread_join () from /usr/lib/libpthread.so.0
#1  0x00007f7ad50a7f2d in libtorrent::session::~session() () from /usr/lib/libtorrent-rasterbar.so.9
#2  0x00007f7ad5561c0d in ?? () from /usr/lib/python3.5/site-packages/libtorrent.cpython-35m-x86_64-linux-gnu.so
#3  0x00007f7ad55672d9 in ?? () from /usr/lib/python3.5/site-packages/libtorrent.cpython-35m-x86_64-linux-gnu.so
#4  0x00007f7ad4ae4ecc in ?? () from /usr/lib/libboost_python3.so.1.61.0
#5  0x00007f7ad696cc7a in ?? () from /usr/lib/libpython3.5m.so.1.0
#6  0x00007f7ad694f9a7 in ?? () from /usr/lib/libpython3.5m.so.1.0
#7  0x00007f7ad69507d0 in ?? () from /usr/lib/libpython3.5m.so.1.0
#8  0x00007f7ad695d0b7 in ?? () from /usr/lib/libpython3.5m.so.1.0
#9  0x00007f7ad69513cb in ?? () from /usr/lib/libpython3.5m.so.1.0
#10 0x00007f7ad69e7581 in PyImport_Cleanup () from /usr/lib/libpython3.5m.so.1.0
#11 0x00007f7ad69f1bb4 in Py_Finalize () from /usr/lib/libpython3.5m.so.1.0
#12 0x00007f7ad6a0cd9e in Py_Main () from /usr/lib/libpython3.5m.so.1.0
#13 0x0000000000400af0 in main ()
```

**Comment by arvidn** [comment]
it hangs when python exits and destructs the session I take it?

**Comment by aresch** [comment]
Yes.

**Comment by aresch** [comment]
Looks like this happens without even adding the torrent to the session.

```
import libtorrent as lt
s = lt.session({})
```
Something has changed recently, because the reason I found this was that my tests would hang.  The tests create and destroy a lot of libtorrent sessions.  I am going to try an older version of boost.

**Comment by arvidn** [comment]
thanks for the report! I believe this fixes it: https://github.com/arvidn/libtorrent/pull/1203

**Comment by aresch** [comment]
Yes, that patch fixes the issue for me.

**Comment by arvidn** [comment]
thanks!
