### ISSUE TITLE
Assertion at random times

### ISSUE THREAD

**Issue by JosefVitu** [arvidn/libtorrent#1314]
libtorrent version (or branch): [1.0.10](https://github.com/arvidn/libtorrent/releases/tag/libtorrent-1_0_10)
`./configure --enable-debug --enable-encryption`
platform/architecture: Linux 4.7.8 x86_64
compiler and compiler version: g++ (Debian 6.2.0-10) 6.2.0
Boost: 1.62.0.1

Hello, I'm getting assertion fails at seemingly random times using qBittorrent (build from master), always with the following backtrace:
```
#0  0x00007f187f75dfdf in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
#1  0x00007f187f75f40a in __GI_abort () at abort.c:89
#2  0x00007f1881ced0c7 in assert_fail(char const*, int, char const*, char const*, char const*, int) (expr=expr@entry=0x7f1881f95cc8 "ec != error::invalid_argument || !m_outgoing", line=line@entry=3562, file=file@entry=0x7f1881fbbcee "peer_connection.cpp", function=function@entry=0x7f1881f99820 <libtorrent::peer_connection::disconnect(boost::system::error_code const&, int)::__PRETTY_FUNCTION__> "virtual void libtorrent::peer_connection::disconnect(const boost::system::error_code&, int)", value=value@entry=0x7f1881f92c9e "", kind=kind@entry=0) at assert.cpp:267
#3  0x00007f1881dc5526 in libtorrent::peer_connection::disconnect(boost::system::error_code const&, int) (this=0x7f184804e860, ec=..., error=0) at peer_connection.cpp:3562
#4  0x00007f1881db0b56 in libtorrent::peer_connection::connect_failed(boost::system::error_code const&) (this=this@entry=0x7f184804e860, e=...) at peer_connection.cpp:3497
#5  0x00007f1881dc2163 in libtorrent::peer_connection::on_connection_complete(boost::system::error_code const&) (this=0x7f184804e860, e=...) at peer_connection.cpp:5615
#6  0x00007f1881f3e746 in boost::asio::detail::completion_handler<boost::_bi::bind_t<void, boost::function1<void, boost::system::error_code const&>, boost::_bi::list1<boost::_bi::value<boost::system::error_code> > > >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) (a0=..., this=0x7f1860f61b60) at /usr/include/boost/function/function_template.hpp:771
#7  0x00007f1881f3e746 in boost::asio::detail::completion_handler<boost::_bi::bind_t<void, boost::function1<void, boost::system::error_code const&>, boost::_bi::list1<boost::_bi::value<boost::system::error_code> > > >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) (a=<synthetic pointer>, f=..., this=0x7f1860f61b80) at /usr/include/boost/bind/bind.hpp:259
#8  0x00007f1881f3e746 in boost::asio::detail::completion_handler<boost::_bi::bind_t<void, boost::function1<void, boost::system::error_code const&>, boost::_bi::list1<boost::_bi::value<boost::system::error_code> > > >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) (this=0x7f1860f61b60) at /usr/include/boost/bind/bind.hpp:1294
#9  0x00007f1881f3e746 in boost::asio::detail::completion_handler<boost::_bi::bind_t<void, boost::function1<void, boost::system::error_code const&>, boost::_bi::list1<boost::_bi::value<boost::system::error_code> > > >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) (function=...) at /usr/include/boost/asio/handler_invoke_hook.hpp:69
#10 0x00007f1881f3e746 in boost::asio::detail::completion_handler<boost::_bi::bind_t<void, boost::function1<void, boost::system::error_code const&>, boost::_bi::list1<boost::_bi::value<boost::system::error_code> > > >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) (context=..., function=...) at /usr/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#11 0x00007f1881f3e746 in boost::asio::detail::completion_handler<boost::_bi::bind_t<void, boost::function1<void, boost::system::error_code const&>, boost::_bi::list1<boost::_bi::value<boost::system::error_code> > > >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) (owner=0x564b7bbac200, base=0x7f184803e320) at /usr/include/boost/asio/detail/completion_handler.hpp:68
#12 0x00007f1881ce434b in boost::asio::detail::task_io_service::do_run_one(boost::asio::detail::scoped_lock<boost::asio::detail::posix_mutex>&, boost::asio::detail::task_io_service_thread_info&, boost::system::error_code const&) (bytes_transferred=<optimized out>, ec=..., owner=..., this=<optimized out>) at /usr/include/boost/asio/detail/task_io_service_operation.hpp:38
#13 0x00007f1881ce434b in boost::asio::detail::task_io_service::do_run_one(boost::asio::detail::scoped_lock<boost::asio::detail::posix_mutex>&, boost::asio::detail::task_io_service_thread_info&, boost::system::error_code const&) (this=this@entry=0x564b7bbac200, lock=..., this_thread=..., ec=...) at /usr/include/boost/asio/detail/impl/task_io_service.ipp:372
#14 0x00007f1881ce44d1 in boost::asio::detail::task_io_service::run(boost::system::error_code&) (this=0x564b7bbac200, ec=...)
    at /usr/include/boost/asio/detail/impl/task_io_service.ipp:149
#15 0x00007f1881ce4629 in boost::asio::io_service::run(boost::system::error_code&) (this=this@entry=0x564b7bbaa398, ec=...)
    at /usr/include/boost/asio/impl/io_service.ipp:66
#16 0x00007f1881e4b86c in libtorrent::aux::session_impl::main_thread() (this=0x564b7bba9f10) at session_impl.cpp:4903
#17 0x00007f1881ce72ca in boost::asio::detail::boost_asio_detail_posix_thread_function(void*) (arg=0x564b7bbaf260)
    at /usr/include/boost/asio/detail/impl/posix_thread.ipp:64
#18 0x00007f18805e0464 in start_thread (arg=0x7f1860f62700) at pthread_create.c:333
#19 0x00007f187f8139df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
```

There are two idle torrents loaded, connecting to two trackers (one of them not working). DHT, PeX and LSD enabled and working.

Is there something I can do to help with debugging?

**Comment by arvidn** [comment]
Is this happening with both in master and 1.0.x?

This error indicates that accepting an incoming connection fails with EINVAL. Which is weird. It's not an assert that necessarily suggests an internal inconsistency though. It should be safe to remove/ignore it

**Comment by ssiloti** [comment]
That assertion has been commented out on master and RC_1_1 since 2014. See 7351389c

**Comment by JosefVitu** [comment]
@arvidn Cannot confirm on master, as qBittorrent FTBFS for me with >=1.1.1 (haven't looked at the cause thoroughly yet).
@ssiloti I see. I'll comment it out for myself in 1.0.10 as well and see what happens.

Thank you both.
