### ISSUE TITLE
Python: cannot access some fields of add_torrent_params

### ISSUE THREAD

**Issue by aresch** [arvidn/libtorrent#2701]
Branch: master

Trying to access some fields from the add_torrent_params generated in a save_resume_data_alert fails.

The attributes: verified_pieces, unfinished_pieces, renamed_files, have_pieces

```
>>> print(alert.__class__)
<class 'libtorrent.save_resume_data_alert'>
>>> print(alert.params.verified_pieces)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: No to_python (by-value) converter found for C++ type: libtorrent::typed_bitfield<libtorrent::aux::strong_typedef<int, libtorrent::aux::piece_index_tag, void> >
>>> print(alert.params.unfinished_pieces)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: No to_python (by-value) converter found for C++ type: libtorrent::aux::noexcept_movable<std::map<libtorrent::aux::strong_typedef<int, libtorrent::aux::piece_index_tag, void>, libtorrent::bitfield, std::less<libtorrent::aux::strong_typedef<int, libtorrent::aux::piece_index_tag, void> >, std::allocator<std::pair<libtorrent::aux::strong_typedef<int,
libtorrent::aux::piece_index_tag, void> const, libtorrent::bitfield> > > >
>>> print(alert.params.renamed_files)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: No to_python (by-value) converter found for C++ type: libtorrent::aux::noexcept_movable<std::map<libtorrent::aux::strong_typedef<int, libtorrent::aux::file_index_tag, void>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<libtorrent::aux::strong_typedef<int, libtorrent::aux::file_index_tag, void> >, std::allocator<std::pair<libtorrent::aux::strong_typedef<int, libtorrent::aux::file_index_tag, void> const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >
>>> print(alert.params.have_pieces)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: No to_python (by-value) converter found for C++ type: libtorrent::typed_bitfield<libtorrent::aux::strong_typedef<int, libtorrent::aux::piece_index_tag, void> >
```

**Comment by arvidn** [comment]
does this fix it? https://github.com/arvidn/libtorrent/pull/2705
