### ISSUE TITLE
The pythin binding isn't linked to libraries

### ISSUE THREAD

**Issue by yurivict** [arvidn/libtorrent#3330]
```
$ deluged 
[yuri@yv /usr/ports/net-p2p/py-libtorrent-rasterbar]$ [ERROR   ] 15:56:02 main:248 /usr/local/lib/python2.7/site-packages/libtorrent.so: Undefined symbol "_ZTIN5boost6python15instance_holderE"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/deluge/main.py", line 241, in start_daemon
    Daemon(options, args)
  File "/usr/local/lib/python2.7/site-packages/deluge/core/daemon.py", line 144, in __init__
    from deluge.core.core import Core
  File "/usr/local/lib/python2.7/site-packages/deluge/core/core.py", line 38, in <module>
    from deluge._libtorrent import lt
  File "/usr/local/lib/python2.7/site-packages/deluge/_libtorrent.py", line 59, in <module>
    import libtorrent as lt
ImportError: /usr/local/lib/python2.7/site-packages/libtorrent.so: Undefined symbol "_ZTIN5boost6python15instance_holderE"
```

```
$ LD_PRELOAD=/usr/local/lib/libboost_python27.so deluged 
/usr/local/lib/libboost_python27.so: Undefined symbol "PyProperty_Type"
[yuri@yv /usr/ports/net-p2p/py-libtorrent-rasterbar]$ /usr/local/lib/libboost_python27.so: Undefined symbol "PyProperty_Type"
/usr/local/lib/libboost_python27.so: Undefined symbol "PyProperty_Type"
/usr/local/lib/libboost_python27.so: Undefined symbol "PyProperty_Type"
[ERROR   ] 15:57:17 main:248 /usr/local/lib/libtorrent-rasterbar.so.9: Undefined symbol "libiconv"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/deluge/main.py", line 241, in start_daemon
    Daemon(options, args)
  File "/usr/local/lib/python2.7/site-packages/deluge/core/daemon.py", line 144, in __init__
    from deluge.core.core import Core
  File "/usr/local/lib/python2.7/site-packages/deluge/core/core.py", line 38, in <module>
    from deluge._libtorrent import lt
  File "/usr/local/lib/python2.7/site-packages/deluge/_libtorrent.py", line 59, in <module>
    import libtorrent as lt
ImportError: /usr/local/lib/libtorrent-rasterbar.so.9: Undefined symbol "libiconv"
```

**Comment by arvidn** [comment]
how are you building?
using boost-build is probably the most reliable way to get it to work.

**Comment by yurivict** [comment]
I build ```libtorrent-rasterbar``` with cmake, and ```py-libtorrent-rasterbar``` with python's ```distutils```.

**Comment by arvidn** [comment]
unfortunately neither of those build systems are very good for ABI compatibility. Ideally distutils would only be used for building a package, not for building (like it is on windows).

If you build everything with boost-build it works correctly, and possibly if you build both with cmake too.

pull requests are welcome to improve this!
