### ISSUE TITLE
assert in client_test when adding a magnet link with embedded trackers

### ISSUE THREAD

**Issue by ssiloti** [arvidn/libtorrent#3352]
libtorrent version (or branch): libtorrent-1_2_0_RC

platform/architecture: linux/x86-64

compiler and compiler version: gcc 8.2.0

Probably just needs a check for `ti->is_valid()` before calling `ti->num_pieces()`.

```
#0  raise (sig=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x0000555555f719fb in libtorrent::assert_fail (expr=0x5555563fe2ff "m_piece_length > 0", line=379, file=0x5555563fe2d8 "../include/libtorrent/file_storage.hpp",
    function=0x5555563fe680 <libtorrent::file_storage::num_pieces() const::__PRETTY_FUNCTION__> "int libtorrent::file_storage::num_pieces() const", value=0x0, kind=0)
    at ../src/assert.cpp:380
#2  0x0000555555f4df33 in libtorrent::file_storage::num_pieces (this=0x7ffff0017400) at ../include/libtorrent/file_storage.hpp:379
#3  0x0000555555f4df54 in libtorrent::torrent_info::num_pieces (this=0x7ffff0017400) at ../include/libtorrent/torrent_info.hpp:334
#4  0x0000555555f4d028 in torrent_view::print_torrent (this=0x7fffffffd770, s=..., selected=true) at torrent_view.cpp:391
#5  0x0000555555f4cb31 in torrent_view::render (this=0x7fffffffd770) at torrent_view.cpp:314
#6  0x0000555555f4c4c4 in torrent_view::update_torrents (this=0x7fffffffd770, st=std::vector of length 1, capacity 1 = {...}) at torrent_view.cpp:198
#7  0x0000555555f00ac5 in handle_alert (view=..., ses_view=..., a=0x7ffff001a3c8) at client_test.cpp:883
#8  0x0000555555f00d41 in pop_alerts (view=..., ses_view=..., ses=..., events=std::deque with 19 elements = {...}) at client_test.cpp:905
#9  0x0000555555f044f0 in main (argc=4, argv=0x7fffffffe5a8) at client_test.cpp:1631
```

**Comment by arvidn** [comment]
The stack trace looks like it’s more related to just magnets, and not necessarily magnets with trackers
