### ISSUE TITLE
Error when adding HTTP/URL seed to a torrent from Python

### ISSUE THREAD

**Issue by devos50** [arvidn/libtorrent#3726]
When creating a torrent file using libtorrent, and adding URL/HTTP seeds to it from Python, there is a crash:

```
======================================================================
ERROR: test_create_torrent_one_file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/Library/Python/2.7/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "/Library/Python/2.7/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/Users/martijndevos/Documents/tribler/Tribler/Test/test_as_server.py", line 62, in check
    result = fun(*argv, **kwargs)
  File "/Users/martijndevos/Documents/tribler/Tribler/Test/Core/test_torrent_utils.py", line 22, in test_create_torrent_one_file
    result = create_torrent_file([os.path.join(self.TORRENT_DATA_DIR, self.FILE1_NAME)], self.get_params())
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/Utilities/torrent_utils.py", line 92, in create_torrent_file
    torrent.add_http_seed(params['httpseeds'])
ArgumentError: Python argument types in
    create_torrent.add_http_seed(create_torrent, str)
did not match C++ signature:
    add_http_seed(libtorrent::create_torrent {lvalue}, boost::basic_string_view<char, std::__1::char_traits<char> >)
```

This also happens when invoking the `add_url_seed` method.

**Comment by arvidn** [comment]
this should do it: https://github.com/arvidn/libtorrent/pull/3733
