### ISSUE TITLE
AttributeError: module 'libtorrent' has no attribute 'add_torrent_params_flags_t'

### ISSUE THREAD

**Issue by perfect7gentleman** [arvidn/libtorrent#3790]
**Please provide the following information**

libtorrent version (or branch): RC_1_2

platform/architecture: amd64

compiler and compiler version: GCC-8.3

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
Deluge-2.0 (develop branch built with Python-3.7)
```
~ $ deluged
Traceback (most recent call last):
  File "/usr/bin/deluged", line 11, in <module>
    load_entry_point('deluge==2.0.0b2.dev316', 'console_scripts', 'deluged')()
  File "/usr/lib/python3.7/site-packages/deluge/core/daemon_entry.py", line 90, in start_daemon
    from deluge.core.daemon import is_daemon_running
  File "/usr/lib/python3.7/site-packages/deluge/core/daemon.py", line 22, in <module>
    from deluge.core.core import Core
  File "/usr/lib/python3.7/site-packages/deluge/core/core.py", line 43, in <module>
    from deluge.core.torrentmanager import TorrentManager
  File "/usr/lib/python3.7/site-packages/deluge/core/torrentmanager.py", line 50, in <module>
    | lt.add_torrent_params_flags_t.flag_apply_ip_filter
AttributeError: module 'libtorrent' has no attribute 'add_torrent_params_flags_t'
```

**Comment by joriscarrier** [comment]
`add_torrent_params_flags_t` is a deprecated functions, you can build with `deprecated-functions=on` or use torrent_flags object:
```

**Comment by perfect7gentleman** [comment]
thanx
