### ISSUE TITLE
Tests aren't python3 compatible

### ISSUE THREAD

**Issue by yurivict** [arvidn/libtorrent#4597]
Version libtorrent-rasterbar-1.2.6 on FreeBSD 12.1

python-2.7 is EOLed.

Particularly, ```test_http_connection``` fails with python-3.7 seemingly because of python syntax incompatibility:
```
 ===== TESTING: https://non-existent-domain.se/non-existing-file =====
00:00:01.096 expecting: size: -1 status: -1 connected: 0 error: no error
00:00:01.139 < -1 
00:00:01.139 connect_handler_called: 0
00:00:01.139 handler_called: 1
00:00:01.139 status: 0
00:00:01.139 size: 0
00:00:01.139 expected-size: -1
00:00:01.139 error_code: Host not found (authoritative)
stopping web server
killing pid: 16910
cwd: /usr/ports/net-p2p/libtorrent-rasterbar/work/.build/test/test_tmp_16909_1
Unhandled exception in thread started by <class '__main__.ConnectionHandler'>
Traceback (most recent call last):
  File "../http.py", line 111, in __init__
Unhandled exception in thread started by <class '__main__.ConnectionHandler'>
Traceback (most recent call last):
  File "../http.py", line 111, in __init__
    self.method, self.path, self.protocol = self.get_base_header()
  File "../http.py", line 144, in get_base_header
    self.method, self.path, self.protocol = self.get_base_header()
  File "../http.py", line 144, in get_base_header
    self.client_buffer += self.client.recv(BUFLEN)
TypeError: can only concatenate str (not "bytes") to str
    self.client_buffer += self.client.recv(BUFLEN)
TypeError: can only concatenate str (not "bytes") to str
Unhandled exception in thread started by <class '__main__.ConnectionHandler'>
Traceback (most recent call last):
  File "../http.py", line 111, in __init__
    self.method, self.path, self.protocol = self.get_base_header()
  File "../http.py", line 144, in get_base_header
    self.client_buffer += self.client.recv(BUFLEN)
TypeError: can only concatenate str (not "bytes") to str
Unhandled exception in thread started by <class '__main__.ConnectionHandler'>
Traceback (most recent call last):
  File "../http.py", line 111, in __init__
    self.method, self.path, self.protocol = self.get_base_header()
  File "../http.py", line 144, in get_base_header
    self.client_buffer += self.client.recv(BUFLEN)
TypeError: can only concatenate str (not "bytes") to str
Unhandled exception in thread started by <class '__main__.ConnectionHandler'>
Traceback (most recent call last):
  File "../http.py", line 111, in __init__
    self.method, self.path, self.protocol = self.get_base_header()
  File "../http.py", line 144, in get_base_header
    self.client_buffer += self.client.recv(BUFLEN)
TypeError: can only concatenate str (not "bytes") to str
Unhandled exception in thread started by <class '__main__.ConnectionHandler'>
Traceback (most recent call last):
  File "../http.py", line 111, in __init__
    self.method, self.path, self.protocol = self.get_base_header()
  File "../http.py", line 144, in get_base_header
    self.client_buffer += self.client.recv(BUFLEN)
TypeError: can only concatenate str (not "bytes") to str
Unhandled exception in thread started by <class '__main__.ConnectionHandler'>
Traceback (most recent call last):
  File "../http.py", line 111, in __init__
    self.method, self.path, self.protocol = self.get_base_header()
  File "../http.py", line 144, in get_base_header
    self.client_buffer += self.client.recv(BUFLEN)
TypeError: can only concatenate str (not "bytes") to str
Unhandled exception in thread started by <class '__main__.ConnectionHandler'>
Traceback (most recent call last):
  File "../http.py", line 111, in __init__
    self.method, self.path, self.protocol = self.get_base_header()
  File "../http.py", line 144, in get_base_header
    self.client_buffer += self.client.recv(BUFLEN)
TypeError: can only concatenate str (not "bytes") to str
Unhandled exception in thread started by <class '__main__.ConnectionHandler'>
Traceback (most recent call last):
  File "../http.py", line 111, in __init__
    self.method, self.path, self.protocol = self.get_base_header()
  File "../http.py", line 144, in get_base_header
    self.client_buffer += self.client.recv(BUFLEN)
TypeError: can only concatenate str (not "bytes") to str
^CTraceback (most recent call last):
Traceback (most recent call last):
  File "../http.py", line 248, in <module>
  File "../web_server.py", line 211, in <module>
    httpd.handle_request()
  File "/usr/local/lib/python3.7/socketserver.py", line 294, in handle_request
    start_server(port=listen_port)
  File "../http.py", line 226, in start_server
    ready = selector.select(timeout)
  File "/usr/local/lib/python3.7/selectors.py", line 415, in select
    thread.start_new_thread(handler, soc.accept() + (timeout,))
  File "/usr/local/lib/python3.7/socket.py", line 212, in accept
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
[yuri@yv /usr/ports/net-p2p/libtorrent-rasterbar/work/.build/test]$     fd, addr = self._accept()
```

**Comment by arvidn** [comment]
yes, the python scripts used for test helpers (web server and socks proxy) are python 2. I've made some attempts to convert them but it's always failed on at least one CI.

**Comment by arvidn** [comment]
patches are welcome!

**Comment by arvidn** [comment]
I believe this has been fixed no, right?
