### ISSUE TITLE
assertion failure m_num_pieces == m_have_piece.count()

### ISSUE THREAD

**Issue by tghosgor** [arvidn/libtorrent#4831]
Can't seem to do anything specific to reproduce this. It seems to happen randomly. The operation I did was to add a number of torrents and remove them in a sliding window (in upload mode).

libtorrent 1.2.7

arch linux amd64

gcc version 10.1.0 (GCC)

Normal operation as far as I can say. Built with --enable-debug --enable-invariant + arch default options.
version: 1.2.7.0-3ed6fa64f

file: '../../libtorrent-rasterbar-1.2.7/src/peer_connection.cpp'
line: 786
function: init
expression: m_num_pieces == m_have_piece.count()

stack:
1: libtorrent::assert_fail(char const*, int, char const*, char const*, char const*, int)

**Comment by arvidn** [comment]
the stack trace would be even more useful here. could you try building with `-export-dynamic` in `CXXFLAGS` and `-rdynamic` in `LDFLAGS`?

**Comment by arvidn** [comment]
actually, I think I know what's happening here

**Comment by arvidn** [comment]
I found [this](https://github.com/arvidn/libtorrent/blob/RC_1_2/src/peer_connection.cpp#L1921).

Is it possible the torrents this happens with have more than 524288 pieces?

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/4846

**Comment by arvidn** [comment]
somewhat related: https://github.com/arvidn/libtorrent/pull/4847

**Comment by tghosgor** [comment]
> Is it possible the torrents this happens with have more than 524288 pieces?

If this means that it should always happen with a specific torrent, then maybe not. I may try to track the torrent that that causes this but it is not always happening (and I should be processing the same torrent after the crash in an effort to retry).

I can confirm I did not experience this on 2.0 branch.

**Comment by arvidn** [comment]
yeah, I imagine for this to happen certain events would have to be ordered just right. like connecting to the peer, receiving a have-all message and receiving the metadata. So, I was thinking that another condition for it to be *possible* to happen could be that the torrent is large. I haven't worked out a sequence of events where it would happen, but it might be a hint to narrow down the search.

**Comment by tghosgor** [comment]
Here is the stack trace.

```
#0  0x00007ffff722e7e5 in raise () from /usr/lib/libpthread.so.0
#1  0x00007ffff799f2d1 in libtorrent::assert_fail (expr=expr@entry=0x7ffff7d5a530 "m_num_pieces == m_have_piece.count()", line=line@entry=786, file=file@entry=0x7ffff7d59a78 "../../libtorrent-rasterbar-1.2.7/src/peer_connection.cpp", function=function@entry=0x7ffff7d60aa1 "init", value=value@entry=0x0, 
    kind=kind@entry=0) at ../../libtorrent-rasterbar-1.2.7/src/assert.cpp:380
#2  0x00007ffff7ac0cad in libtorrent::peer_connection::init (this=0x55555733c790) at ../../libtorrent-rasterbar-1.2.7/src/peer_connection.cpp:786
#3  0x00007ffff7c2d750 in libtorrent::torrent::init (this=this@entry=0x555558bcb120) at /usr/include/c++/10.1.0/bits/shared_ptr_base.h:1324
#4  0x00007ffff7c387a0 in libtorrent::torrent::set_metadata (this=this@entry=0x555558bcb120, metadata_buf=...) at ../../libtorrent-rasterbar-1.2.7/src/torrent.cpp:6906
#5  0x00007ffff7ccc447 in libtorrent::(anonymous namespace)::ut_metadata_plugin::received_metadata (this=this@entry=0x5555564e2010, source=..., buf=..., piece=piece@entry=0, total_size=total_size@entry=3882) at ../../libtorrent-rasterbar-1.2.7/include/libtorrent/span.hpp:79
#6  0x00007ffff7cccd3a in libtorrent::(anonymous namespace)::ut_metadata_peer_plugin::on_extended (this=0x555555fc5470, length=<optimized out>, extended_msg=<optimized out>, body=...) at ../../libtorrent-rasterbar-1.2.7/include/libtorrent/span.hpp:121
#7  0x00007ffff79cb8f5 in libtorrent::bt_peer_connection::on_extended (this=this@entry=0x55555733c790, received=received@entry=2492) at ../../libtorrent-rasterbar-1.2.7/src/bt_peer_connection.cpp:1665
#8  0x00007ffff79cbd4e in libtorrent::bt_peer_connection::dispatch_message (this=this@entry=0x55555733c790, received=received@entry=2492) at ../../libtorrent-rasterbar-1.2.7/src/bt_peer_connection.cpp:1855
#9  0x00007ffff79d3356 in libtorrent::bt_peer_connection::on_receive_impl (this=this@entry=0x55555733c790, bytes_transferred=2492) at ../../libtorrent-rasterbar-1.2.7/src/bt_peer_connection.cpp:3358
#10 0x00007ffff79d3a4c in libtorrent::bt_peer_connection::on_receive (this=0x55555733c790, error=..., bytes_transferred=<optimized out>) at ../../libtorrent-rasterbar-1.2.7/src/bt_peer_connection.cpp:2448
#11 0x00007ffff7ad0f90 in libtorrent::peer_connection::on_receive_data (this=0x55555733c790, error=..., bytes_transferred=<optimized out>) at ../../libtorrent-rasterbar-1.2.7/src/peer_connection.cpp:5983
#12 0x00007ffff7ae9584 in std::__invoke_impl<void, void (libtorrent::peer_connection::* const&)(boost::system::error_code const&, unsigned long), std::shared_ptr<libtorrent::peer_connection> const&, boost::system::error_code const&, unsigned long const&> (
    __t=std::shared_ptr<libtorrent::peer_connection> (use count 4, weak count 1) = {...}, __f=
    @0x7fffffffd650: (void (libtorrent::peer_connection::*)(libtorrent::peer_connection * const, const boost::system::error_code &, unsigned long)) 0x7ffff7ad09c2 <libtorrent::peer_connection::on_receive_data(boost::system::error_code const&, unsigned long)>) at /usr/include/c++/10.1.0/bits/shared_ptr_base.h:1324
#13 std::__invoke<void (libtorrent::peer_connection::* const&)(boost::system::error_code const&, unsigned long), std::shared_ptr<libtorrent::peer_connection> const&, boost::system::error_code const&, unsigned long const&> (__fn=
    @0x7fffffffd650: (void (libtorrent::peer_connection::*)(libtorrent::peer_connection * const, const boost::system::error_code &, unsigned long)) 0x7ffff7ad09c2 <libtorrent::peer_connection::on_receive_data(boost::system::error_code const&, unsigned long)>) at /usr/include/c++/10.1.0/bits/invoke.h:95
#14 std::_Bind<void (libtorrent::peer_connection::*(std::shared_ptr<libtorrent::peer_connection>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>::__call_c<void, boost::system::error_code const&, unsigned long const&, 0ul, 1ul, 2ul>(std::tuple<boost::system::error_code const&, unsigned long const&>&&, std::_Index_tuple<0ul, 1ul, 2ul>) const (__args=..., this=0x7fffffffd650) at /usr/include/c++/10.1.0/functional:427
#15 std::_Bind<void (libtorrent::peer_connection::*(std::shared_ptr<libtorrent::peer_connection>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>::operator()<boost::system::error_code const&, unsigned long const&, void>(boost::system::error_code const&, unsigned long const&) const (this=0x7fffffffd650) at /usr/include/c++/10.1.0/functional:511
#16 libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::peer_connection::*(std::shared_ptr<libtorrent::peer_connection>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, 432ul>::operator()<boost::system::error_code const&, unsigned long const&>(boost::system::error_code const&, unsigned long const&) const (this=this@entry=0x7fffffffd650) at ../../libtorrent-rasterbar-1.2.7/include/libtorrent/aux_/allocating_handler.hpp:101
#17 0x00007ffff7b0024d in boost::asio::detail::binder2<libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::peer_connection::*(std::shared_ptr<libtorrent::peer_connection>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, 432ul>, boost::system::error_code, unsigned long>::operator()() (this=0x7fffffffd650) at /usr/include/boost/asio/detail/bind_handler.hpp:162
#18 boost::asio::asio_handler_invoke<boost::asio::detail::binder2<libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::peer_connection::*(std::shared_ptr<libtorrent::peer_connection>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, 432ul>, boost::system::error_code, unsigned long> >(boost::asio::detail::binder2<libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::peer_connection::*(std::shared_ptr<libtorrent::peer_connection>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, 432ul>, boost::system::error_code, unsigned long>&, ...) (function=...) at /usr/include/boost/asio/handler_invoke_hook.hpp:69
#19 boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::binder2<libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::peer_connection::*(std::shared_ptr<libtorrent::peer_connection>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, 432ul>, boost::system::error_code, unsigned long>, libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::peer_connection::*(std::shared_ptr<libtorrent::peer_connection>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, 432ul> >(boost::asio::detail::binder2<libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::peer_connection::*(std::shared_ptr<libtorrent::peer_connection>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, 432ul>, boost::system::error_code, unsigned long>&, libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::peer_connection::*(std::shared_ptr<libtorrent::peer_connection>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, 432ul>&) (context=..., function=...) at /usr/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#20 boost::asio::detail::asio_handler_invoke<boost::asio::detail::binder2<libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::peer_connection::*(std::shared_ptr<libtorrent::peer_connection>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, 432ul>, boost::system::error_code, unsigned long>, libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::peer_connection::*(std::shared_ptr<libtorrent::peer_connection>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, 432ul>, boost::system::error_code, unsigned long>(boost::asio::detail::binder2<libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::peer_connection::*(std::shared_ptr<libtorrent::peer_connection>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, 432ul>, boost::system::error_code, unsigned long>&, boost::asio::detail::binder2<libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::peer_connection::*(std::shared_ptr<libtorrent::peer_connection>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, 432ul>, boost::system::error_code, unsigned long>*) (this_handler=0x7fffffffd650, 
    function=...) at /usr/include/boost/asio/detail/bind_handler.hpp:207
#21 boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::binder2<libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::peer_connection::*(std::shared_ptr<libtorrent::peer_connection>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, 432ul>, boost::system::error_code, unsigned long>, boost::asio::detail::binder2<libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::peer_connection::*(std::shared_ptr<libtorrent::peer_connection>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, 432ul>, boost::system::error_code, unsigned long> >(boost::asio::detail::binder2<libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::peer_connection::*(std::shared_ptr<libtorrent::peer_connection>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, 432ul>, boost::system::error_code, unsigned long>&, boost::asio::detail::binder2<libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::peer_connection::*(std::shared_ptr<libtorrent::peer_connection>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, 432ul>, boost::system::error_code, unsigned long>&) (
    context=..., function=...) at /usr/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#22 boost::asio::detail::io_object_executor<boost::asio::executor>::dispatch<boost::asio::detail::binder2<libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::peer_connection::*(std::shared_ptr<libtorrent::peer_connection>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, 432ul>, boost::system::error_code, unsigned long>, std::allocator<void> >(boost::asio::detail::binder2<libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::peer_connection::*(std::shared_ptr<libtorrent::peer_connection>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, 432ul>, boost::system::error_code, unsigned long>&&, std::allocator<void> const&) const (a=..., f=..., this=0x7fffffffd640) at /usr/include/boost/asio/detail/io_object_executor.hpp:119
#23 boost::asio::detail::handler_work<libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::peer_connection::*(std::shared_ptr<libtorrent::peer_connection>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, 432ul>, boost::asio::detail::io_object_executor<boost::asio::executor>, boost::asio::detail::io_object_executor<boost::asio::executor> >::complete<boost::asio::detail::binder2<libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::peer_connection::*(std::shared_ptr<libtorrent::peer_connection>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, 432ul>, boost::system::error_code, unsigned long> >(boost::asio::detail::binder2<libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::peer_connection::*(std::shared_ptr<libtorrent::peer_connection>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, 432ul>, boost::system::error_code, unsigned long>&, libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::peer_connection::*(std::shared_ptr<libtorrent::peer_connection>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, 432ul>&) (handler=..., 
    function=..., this=0x7fffffffd630) at /usr/include/boost/asio/detail/handler_work.hpp:72
#24 boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::peer_connection::*(std::shared_ptr<libtorrent::peer_connection>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, 432ul>, boost::asio::detail::io_object_executor<boost::asio::executor> >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) (owner=0x55555563bbe0, base=0x55555733ca70) at /usr/include/boost/asio/detail/reactive_socket_recv_op.hpp:123
#25 0x00007ffff79b07ab in boost::asio::detail::scheduler_operation::complete (bytes_transferred=0, ec=..., owner=0x55555563bbe0, this=<optimized out>) at /usr/include/boost/asio/detail/scheduler_operation.hpp:40
#26 boost::asio::detail::epoll_reactor::descriptor_state::do_complete (owner=0x55555563bbe0, base=<optimized out>, ec=..., bytes_transferred=<optimized out>) at /usr/include/boost/asio/detail/impl/epoll_reactor.ipp:776
#27 0x000055555556d274 in boost::asio::detail::scheduler_operation::complete (this=0x555556d903e0, owner=0x55555563bbe0, ec=..., bytes_transferred=5) at /usr/include/boost/asio/detail/scheduler_operation.hpp:40
#28 0x0000555555571952 in boost::asio::detail::scheduler::do_run_one (this=0x55555563bbe0, lock=..., this_thread=..., ec=...) at /usr/include/boost/asio/detail/impl/scheduler.ipp:447
#29 0x00005555555712b2 in boost::asio::detail::scheduler::run (this=0x55555563bbe0, ec=...) at /usr/include/boost/asio/detail/impl/scheduler.ipp:200
#30 0x0000555555571e56 in boost::asio::io_context::run (this=0x7fffffffd8b0) at /usr/include/boost/asio/impl/io_context.ipp:63
```

**Comment by arvidn** [comment]
so does it still happen with https://github.com/arvidn/libtorrent/pull/4846 applied?

**Comment by tghosgor** [comment]
I am creating a new build with it. Should be able to verify it in a day I guess (it took ~10 hours to reproduce for the stacktrace).

**Comment by tghosgor** [comment]
I haven't experienced any assertions so far, I guess it is fixed.

Thanks for the fast response & solution :smile:.
