### ISSUE TITLE
Alternative for deprecated save_path() method in torrent_handle

### ISSUE THREAD

**Issue by devos50** [arvidn/libtorrent#502]
Hi all,

I'm trying to get libtorrent without deprecated methods working. The project I'm working on uses many deprecated methods in libtorrent so I decided to replace them with newer ones. I encountered a call to `save_path` in a  `torrent_handle` project that has been deprecated. I'm unable to find any (non-deprecated) method that gives me the path where the files of a torrent are saved.

Does anyone know whether and where there is a non-deprecated method to get the save path of a torrent? I'm also using the Python bindings of libtorrent. Many thanks!

**Comment by arvidn** [comment]
torrent_handle::status() and pull out [save_path](http://libtorrent.org/reference-Core.html#save_path) from torrent_status object. An even more efficient way of getting a hold of torrent_status objects is to call [post_torrent_updates()](http://libtorrent.org/reference-Session.html#post_torrent_updates()) on the session, and handle delta updates to all torrents.

**Comment by devos50** [comment]
@arvidn thanks for your suggestion but I get the following stack trace when I try this:

```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 215, in <lambda>
    lm_network_engine_wrapper_created_callback, pstate, initialdlstatus)
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 265, in network_create_engine_wrapper
    self.set_selected_files()
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/Libtorrent/__init__.py", line 13, in invoke_func
    return f(*args, **kwargs)
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 584, in set_selected_files
    unwanteddir_abs = os.path.join(self.handle.status().save_path.decode('utf-8'), unwanteddir)
exceptions.AttributeError: 'torrent_status' object has no attribute 'save_path'
```

Could this be a problem in the Python bindings or in the C++ part of libtorrent?

**Comment by arvidn** [comment]
fix here: https://github.com/arvidn/libtorrent/pull/503
