### ISSUE TITLE
Unresolved soname dependencies:

### ISSUE THREAD

**Issue by perfect7gentleman** [arvidn/libtorrent#5757]
**Please provide the following information**

libtorrent version (or branch): RC_1_2

platform/architecture: Gentoo Linux

compiler and compiler version:
GCC-10.2, Python-3.9, Boost-+1.75

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
emerge =libtorrent-rasterbar-1.2.9999
```
 * /usr/lib/python3.9/site-packages/libtorrent.cpython-39-x86_64-linux-gnu.so
   /usr/lib64/libtorrent-rasterbar.so.10.0.0
 * QA Notice: Unresolved soname dependencies:
 * 
 *      /usr/lib/python3.9/site-packages/libtorrent.cpython-39-x86_64-linux-gnu.so: libtorrent.so.1.2.11
```

**Comment by arvidn** [comment]
is this a bug report?

**Comment by perfect7gentleman** [comment]
I hope so.

**Comment by perfect7gentleman** [comment]
build.log - https://gist.github.com/perfect7gentleman/fd9334d59a369adee76bdd5710e0fa7f

**Comment by perfect7gentleman** [comment]
```
~ $ deluged
 Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/deluge/_libtorrent.py", line 24, in <module>
    import deluge.libtorrent as lt
ModuleNotFoundError: No module named 'deluge.libtorrent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/deluge/_libtorrent.py", line 27, in <module>
    import libtorrent as lt
ImportError: libtorrent.so.1.2.11: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/deluged", line 33, in <module>
    sys.exit(load_entry_point('deluge==2.0.4.dev38', 'console_scripts', 'deluged')())
  File "/usr/lib/python3.9/site-packages/deluge/core/daemon_entry.py", line 90, in start_daemon
    from deluge.core.daemon import is_daemon_running
  File "/usr/lib/python3.9/site-packages/deluge/core/daemon.py", line 22, in <module>
    from deluge.core.core import Core
  File "/usr/lib/python3.9/site-packages/deluge/core/core.py", line 28, in <module>
    from deluge._libtorrent import LT_VERSION, lt
  File "/usr/lib/python3.9/site-packages/deluge/_libtorrent.py", line 29, in <module>
    raise LibtorrentImportError('No libtorrent library found: %s' % (ex))
deluge.error.LibtorrentImportError: No libtorrent library found: libtorrent.so.1.2.11: cannot open shared object file: No such file or directory
```

**Comment by arvidn** [comment]
> No libtorrent library found: libtorrent.so.1.2.11: cannot open shared object file: No such file or directory

It looks like you need to install libtorrent, specifically under the name `libtorrent.so.1.2.11`.

Do you have a library by that name?

**Comment by perfect7gentleman** [comment]
No, no library under that name is installed.

**Comment by perfect7gentleman** [comment]
Moved to CMake. Solved.
