### ISSUE TITLE
libtorrent in Elementum addon

### ISSUE THREAD

**Issue by borisantelo** [arvidn/libtorrent#5798]
libtorrent version (or branch): LibTorrent: 1.1.14.0

platform/architecture: Linux ARM 64-bit version 3.14.29 aarch64

Hi, I was wondering if anybody could help me with this issue about libtorrent on the addon elementum. Sorry if it isn't the correct way, or the correct forum, but I hope somebody could help me. 
I post this issue in elementum forum https://github.com/elgatito/plugin.video.elementum/issues/661. On it I commented: 
"...
I can't use elementum anymore. For a while when I make a search, it scraps the torrents, I choose one of the list, it shows "resolving magnet" and then the message "Playback failed. One or more items failed to play". Thanks"

The developer of elementum implied on a reply that maybe is a libtorent issue, as it does the downloads, and I think the magnet resolving is thru libtorrent.
Here's the log 
https://paste.kodi.tv/ireyebiman
The lines 1743 to 1762 are what I think the most important ones about libtorrent ann the problem
If someone could help please
Thanks

**Comment by arvidn** [comment]
this looks like a problem:

```
2020-12-25 19:35:14.554 T:3465708416  NOTICE: [plugin.video.elementum] [signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0xa41dd0]
```

Do you know where that happens? If you can reproduce it in a debugger (or get a corefile), you may be able to tease out some more details

**Comment by borisantelo** [comment]
@arvidn Thanks for answering. That happens after it gets stuck in resolving magnet, then it's shown the message "Playback failed..." and short after that elementum crashes (that's the line in the log you mention) and then it restarts.
With my limited knowledge the only thing I figured out to do about what you asked  was to set Elementum options to logging in debug level:
http://paste.kodi.tv/adetejagok This is the log I got about the resolving magnets issue
The elementum's developer suggested that I should look if adding torrent files (not magnets) could work, this way it shows the downloading window but never start downloading, it stays buffering with 0 peers 0 seeds, 0 KB/s no matter how long you wait.
http://paste.kodi.tv/ejetujemak This is the log I got when I added a torrent file

Thanks for the help

**Comment by elgatito** [comment]
@arvidn 

```
2020-12-25 19:35:14.554 T:3465708416  NOTICE: [plugin.video.elementum] [signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0xa41dd0]
```

That is caused by trying to get torrent information, while it's being dropped.

User states that magnet cannot be resolved, and torrents are also not being able to start downloading. 
Another device in his network with uTorrent works fine, and on the same device Quasat (with slightly older libtorrent) is also working fine.

No proxy settings, nothing, that I can see.


```
INFO  bittorrent   ▶ configure        [0mListening on: 0.0.0.0:6895,0.0.0.0:6896
INFO  bittorrent   ▶ alertsConsumer   [0mConsuming alerts...
INFO  bittorrent   ▶ startServices    [0mStarting LSD...
INFO  bittorrent   ▶ startServices    [0mStarting DHT...
INFO  bittorrent   ▶ startServices    [0mStarting UPNP...
INFO  bittorrent   ▶ startServices    [0mStarting NATPMP...
NOTI  bittorrent   ▶ logAlerts        [0mlisten_succeeded_alert: successfully listening on [TCP] [::]:6895
NOTI  bittorrent   ▶ logAlerts        [0mlisten_succeeded_alert: successfully listening on [TCP] 0.0.0.0:6895
NOTI  bittorrent   ▶ logAlerts        [0mlisten_succeeded_alert: successfully listening on [TCP] [::]:6896
NOTI  bittorrent   ▶ logAlerts        [0mlisten_succeeded_alert: successfully listening on [TCP] 0.0.0.0:6896
NOTI  bittorrent   ▶ logAlerts        [0mlisten_succeeded_alert: successfully listening on [UDP] 0.0.0.0:6896
INFO  bittorrent   ▶ func1            [0mService started in 135.322625ms
INFO  bittorrent   ▶ startServices    [0mAdding port mapping 6896: 2
INFO  bittorrent   ▶ startServices    [0mAdding port mapping 6895: 3
```

So it should be listening, and UPNP also worked fine, I see no errors, it just not downloading.

**Comment by elgatito** [comment]
@arvidn 

http://paste.kodi.tv/ejetujemak 
Here at the top, I log current torrent information. 
So it has metadata, but trackers list is empty and no connections, waiting or done.

I don't have ideas what to propose there...

**Comment by elgatito** [comment]
@arvidn 
User provided more logs with enabled alerts for all categories.
Adding torrent file: https://paste.kodi.tv/regimofoco
Adding magnet: https://paste.kodi.tv/etaxipabos

**Comment by arvidn** [comment]
none of the stack traces point into libtorrent. The two closest ones are still inside the go-bindings. That's where I think you should start looking. This stack in particular looks suspicious to me:

```
2021-01-13 13:34:28.629 T:3471676288  NOTICE: [plugin.video.elementum] goroutine 2094 [syscall]:
2021-01-13 13:34:28.630 T:3471676288  NOTICE: [plugin.video.elementum] runtime.cgocall(0xa18fc4, 0x23a9974, 0x0)
2021-01-13 13:34:28.631 T:3471676288  NOTICE: [plugin.video.elementum] 	/usr/armv7-linux-gnueabihf/go/src/runtime/cgocall.go:133 +0x5c fp=0x23a995c sp=0x23a9944 pc=0x115248
2021-01-13 13:34:28.631 T:3471676288  NOTICE: [plugin.video.elementum] github.com/ElementumOrg/libtorrent-go._Cfunc__wrap_TorrentInfo_NumPieces_libtorrent_28b3383fcb6c21e7(0x0, 0x0)
2021-01-13 13:34:28.631 T:3471676288  NOTICE: [plugin.video.elementum] 	_cgo_gotypes.go:44238 +0x38 fp=0x23a9970 sp=0x23a995c pc=0x6c67f4
2021-01-13 13:34:28.636 T:3471676288  NOTICE: [plugin.video.elementum] github.com/ElementumOrg/libtorrent-go.SwigcptrTorrentInfo.NumPieces(...)
2021-01-13 13:34:28.637 T:3471676288  NOTICE: [plugin.video.elementum] 	_libtorrent_swig.go:22697
2021-01-13 13:34:28.638 T:3471676288  NOTICE: [plugin.video.elementum] github.com/ElementumOrg/libtorrent-go.(*SwigcptrTorrentInfo).NumPieces(0x15e6098, 0x211b8c0)
```

```
libtorrent-go._Cfunc__wrap_TorrentInfo_NumPieces_libtorrent_28b3383fcb6c21e7(0x0, 0x0)
```

Those two `0x0`, are those the parameters passed in to `torrent_info::num_pieces()`? if so, perhaps a member function is being called on a null pointer.

**Comment by elgatito** [comment]
@arvidn 

> none of the stack traces point into libtorrent. The two closest ones are still inside the go-bindings. That's where I think you should start looking. This stack in particular looks suspicious to me:

That is two minutes after giving up waiting for magnet being resolved. 
Magnet resolve relies on DHT, so let's skip it. Usual torrent from rarbg should work, but trackers list is empty, and there are lot of messages, but I don't know what they mean.

**Comment by arvidn** [comment]
so, the segmentation fault is not the issue. Have you looked at https://libtorrent.org/troubleshooting.html ?

**Comment by borisantelo** [comment]
@arvidn @elgatito Hi, thanks for the replies. Looking the troubleshooting with my little nothing knowledge makes me think is a DHT problem, but I would like of you to consider these alerts
**There are a lot of this kind on the logs**

UPnP: SSDP response from: 192.168.0.14:62759: IP is not a router...
UPnP: invalid URL 192.168.0.14:52794 from 192.168.0.14:62759: unsupported URL protocol...
UPnP: ignoring response from: 192.168.100.3:52141. IP is not on local network...

And this:

[0mdht_log_alert: DHT traversal: [0xe2528c18] ADD id: **0000000000000000000000000000000000000000** addr: 67.215.246.10:6881 distance: 159 invoke-count: 0 type: get_peers
2021-01-13 14:06:37.189 T:3544368000  NOTICE: [plugin.video.elementum] [32mNOTI  bittorrent   ▶ logAlerts        [0mdht_log_alert: DHT traversal: [0xe2528c18] ADD id: 0000000000000000000000000000000000000000 addr: 82.221.103.244:6881 distance: 159 invoke-count: 0 type: get_peers
2021-01-13 14:06:37.190 T:3544368000  NOTICE: [plugin.video.elementum] [32mNOTI  bittorrent   ▶ logAlerts        [0mdht_log_alert: DHT traversal: [0xe2528c18] ADD id: 0000000000000000000000000000000000000000 addr: 87.98.162.88:6881 distance: 159 invoke-count: 0 type: get_peers
2021-01-13 14:06:37.192 T:3544368000  NOTICE: [plugin.video.elementum] [32mNOTI  bittorrent   ▶ logAlerts        [0mdht_log_alert: DHT traversal: [0xe2528c18] ADD id: 0000000000000000000000000000000000000000 addr: 174.129.43.152:6881 distance: 159 invoke-count: 0 type: get_peers
2021-01-13 14:06:37.199 T:3544368000  NOTICE: [plugin.video.elementum] [32mNOTI  bittorrent   ▶ logAlerts        [0mdht_log_alert: DHT traversal: [0xe2528c18] ADD id: 0000000000000000000000000000000000000000 addr: 185.157.221.247:25401 distance: 159 invoke-count: 0 type: get_peers
2021-01-13 14:06:37.202 T:3544368000  NOTICE: [plugin.video.elementum] [32mNOTI  bittorrent   ▶ logAlerts        [0mdht_log_alert: DHT traversal: [0xe2528c18] ADD id: 0000000000000000000000000000000000000000 addr: 212.129.33.59:6881 distance: 159 invoke-count: 0 type: get_peers

are those normal?
And like it's been said quasar works fine in the same network, so the DHT issue is weird to consider.

Thanks for the help. Cheers
