### ISSUE TITLE
2.0.2 build of the Python binding fails because LDFLAGS aren't passed on to the linker

### ISSUE THREAD

**Issue by yurivict** [arvidn/libtorrent#6007]
libtorrent version (or branch): 2.0.2

With this patch:
https://github.com/arvidn/libtorrent/pull/5852/commits/ca9a7f3b89095949e30f533e53080293f33f2f60

platform/architecture: FreeBSD 12.2

compiler and compiler version: clang-10

Linker fails to find libraries because ```LDFLAGS=-L/usr/local/lib```, etc. aren't passed to it:
```
===>  Building for py37-libtorrent-rasterbar-2.0.2
running build
running build_ext
project-config.jam contents:
import feature ;
feature.feature libtorrent-python : on ;
using python : 3.7 : "/usr/local/bin/python3.7" : "/usr/local/include/python3.7m" "/usr/local/include/python3.7m" : : <libtorrent-python>on : "" ;

b2 release address-model=64 libtorrent-python=on python=3.7 python-install-path=/usr/ports/net-p2p/py-libtorrent-rasterbar/work-py37/libtorrent-rasterbar-2.0.2/bindings/python/build/lib.freebsd-12.2-STABLE-amd64-3.7 install_module --project-config=/tmp/tmpmicdgmzq
CXXFLAGS = -O2 -pipe -fno-omit-frame-pointer -DTORRENT_DISABLE_LOGGING -DLIBICONV_PLUG -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -DLIBICONV_PLUG -isystem /usr/local/include 
LDFLAGS =  -fstack-protector-strong -L/usr/local/lib 
OS = FREEBSD
...patience...
...patience...
...patience...
...found 4082 targets...
...updating 2 targets...
clang-linux.link.dll bin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/python-3.7/libtorrent.so
ld: error: unable to find library -lboost_python37
ld: error: unable to find library -lboost_system
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

    "clang++" -L"/usr/local/opt/boost/lib" -o "bin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/python-3.7/libtorrent.so"  -Wl,-soname -Wl,libtorrent.so -shared -Wl,--start-group "bin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/python-3.7/src/module.o" "bin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/python-3.7/src/sha1_hash.o" "bin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/python-3.7/src/converters.o" "bin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/python-3.7/src/create_torrent.o" "bin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/python-3.7/src/fingerprint.o" "bin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/python-3.7/src/utility.o" "bin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/python-3.7/src/session.o" "bin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/python-3.7/src/entry.o" "bin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/python-3.7/src/torrent_info.o" "bin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/python-3.7/src/string.o" "bin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/python-3.7/src/torrent_handle.o" "bin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/python-3.7/src/torrent_status.o" "bin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/python-3.7/src/session_settings.o" "bin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/python-3.7/src/version.o" "bin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/python-3.7/src/alert.o" "bin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/python-3.7/src/datetime.o" "bin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/python-3.7/src/peer_info.o" "bin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/python-3.7/src/ip_filter.o" "bin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/python-3.7/src/magnet_uri.o" "bin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/python-3.7/src/error_code.o" "../../bin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/threading-multi/libtorrent-rasterbar.so.2.0" "../../deps/try_signal/bin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/fpic-on/link-static/threading-multi/libtry_signal.a"  -Wl,-Bstatic -lboost_python37 -Wl,-Bdynamic -lpthread -lboost_system -Wl,--end-group -fPIC -std=c++14 

...failed clang-linux.link.dll bin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/python-3.7/libtorrent.so...
...skipped <p/usr/ports/net-p2p/py-libtorrent-rasterbar/work-py37/libtorrent-rasterbar-2.0.2/bindings/python/build/lib.freebsd-12.2-STABLE-amd64-3.7>libtorrent.so for lack of <pbin/clang-linux-10.0.1/release/address-model-64/cxxstd-14-iso/python-3.7>libtorrent.so...
...failed updating 1 target...
...skipped 1 target...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 269, in <module>
    distclass=B2Distribution,
  File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 180, in run
    self.build_extension_with_b2()
  File "setup.py", line 248, in build_extension_with_b2
    subprocess.run(["b2"] + args, cwd=python_binding_dir, check=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['b2', 'release', 'address-model=64', 'libtorrent-python=on', 'python=3.7', 'python-install-path=/usr/ports/net-p2p/py-libtorrent-rasterbar/work-py37/libtorrent-rasterbar-2.0.2/bindings/python/build/lib.freebsd-12.2-STABLE-amd64-3.7', 'install_module', '--project-config=/tmp/tmpmicdgmzq']' returned non-zero exit status 1.
*** Error code 1
```

**Comment by arvidn** [comment]
The long-term solution for this is to pass in the link flags on the command line, rather than via an environment variable.

However, that patch you point out wasn't supposed to break this ability, in fact, it meant to fix an issue with variable expansion.

I see the Jamfile printing out the `LDFLAGS` it's using as:
```
LDFLAGS =  -fstack-protector-strong -L/usr/local/lib 
```

Which looks correct. I assume `boost_python37` and `boost_system` both exist in `/usr/local/lib`, right?

Could you try running the `b2` command line manually, and add `-an` to it?

```
b2 release address-model=64 libtorrent-python=on python=3.7 python-install-path=/usr/ports/net-p2p/py-libtorrent-rasterbar/work-py37/libtorrent-rasterbar-2.0.2/bindings/python/build/lib.freebsd-12.2-STABLE-amd64-3.7 install_module
```

`-an` will print all of the command lines that would have been executed to rebuild everything (but without executing them). That way we could see which link flags are passed in to the linker command line.

In the upcoming 2.0.3 (currently head of `RC_2_0`) you will be able to add:

```
--b2-args="link-flags=-L$(LDFLAGS)"
```

**Comment by arvidn** [comment]
It just occurred to me that your log already has the command line for the linker step in it. And I see now what's going on.
The `LDFLAGS` are picked up when building `libtorrent`, but they are not picked up when building the python bindings. It's the python bindings that require `boost_python` obviously.

The reason that patch broke it is because in addition to fixing the variable expansion issue, it also removed the `$LDFLAGS` from the `usage-requirements`. i.e. previously those `LDFLAGS` were not just picked up and used when building libtorrent, but also propagated to all targets depending on libtorrent, e.g. the python bindings. That's why it used to work.

I could address this by also making the python bindings honor the `LDFLAGS` environment variable. Maybe that's the simplest short term fix.

**Comment by arvidn** [comment]
This patch is against `RC_1_2`, but it applies cleanly against `RC_2_0` as well. Would you mind giving it a try?

https://github.com/arvidn/libtorrent/pull/6016

**Comment by yurivict** [comment]
This problem is fixed now. Thanks!

**Comment by arvidn** [comment]
thanks!
