### ISSUE TITLE
Segfault with simple example

### ISSUE THREAD

**Issue by elgatito** [arvidn/libtorrent#6028]
**Please provide the following information**

libtorrent version (or branch): latest 1.2.13

platform/architecture: Linux x64

compiler and compiler version: GCC 7.5 / Boost 1.69

Trying to compile simple example:
```

    const lt::alert_category_t alertMask = lt::alert::error_notification
        | lt::alert::file_progress_notification
        | lt::alert::ip_block_notification
        | lt::alert::peer_notification
        | lt::alert::performance_warning
        | lt::alert::port_mapping_notification
        | lt::alert::status_notification
        | lt::alert::storage_notification
        | lt::alert::tracker_notification;

    lt::settings_pack pack;
    lt::session_params sessionParams {pack, {}};
    m_nativeSession = new lt::session {pack};

```

When running I get segfault. GDB output:
```
Starting program: /home/elgato/Develop/lt2http/build/src/lt2http 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff65d9700 (LWP 16195)]
[New Thread 0x7ffff5dd8700 (LWP 16196)]

Thread 1 "lt2http" received signal SIGSEGV, Segmentation fault.
0x0000555555e7bb90 in ?? ()
(gdb) where
#0  0x0000555555e7bb90 in ?? ()
#1  0x00005555555e6af5 in std::_Function_base::~_Function_base() ()
#2  0x0000555555601250 in std::function<std::unique_ptr<libtorrent::dht::dht_storage_interface, std::default_delete<libtorrent::dht::dht_storage_interface> > (libtorrent::dht::dht_settings const&)>::~function()
    ()
#3  0x0000555555601272 in libtorrent::session_params::~session_params() ()
#4  0x000055555560651c in libtorrent::session::start(libtorrent::flags::bitfield_flag<unsigned char, libtorrent::session_flags_tag, void>, libtorrent::settings_pack&&, boost::asio::io_context*) ()
#5  0x000055555560132f in libtorrent::session::session(libtorrent::settings_pack const&, libtorrent::flags::bitfield_flag<unsigned char, libtorrent::session_flags_tag, void>) ()
#6  0x0000555555600c47 in lh::bittorrent::Service::Service() ()
#7  0x00005555555eca53 in lh::Application::Application(int&, char**) ()
#8  0x00005555555e899b in lh::Application::init(int, char**) ()
#9  0x00005555555e6624 in main ()
(gdb) 

```

Maybe missed something? Or missed some flag?

**Comment by elgatito** [comment]
Oh. Recompiled libtorrent with this:

```
./autotool.sh
sed -i 's/$PKG_CONFIG openssl --libs-only-/$PKG_CONFIG openssl --static --libs-only-/' ./configure
./configure --enable-static --disable-shared --disable-deprecated-functions --disable-debug --with-cxx-standard=17
```

And then used also c++17 in my CMAKE and it worked fine. 
Compilation magic..
