### ISSUE TITLE
Build Issue with python bindings

### ISSUE THREAD

**Issue by SSoft7** [arvidn/libtorrent#6176]
**Please provide the following information**

libtorrent version (or branch): `RC_1_2`

platform/architecture: `linux x64`

compiler and compiler version: `gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)`

Issue:

Build command
```
PYTHON="python3" ./configure --enable-dht --enable-encryption --enable-python-binding --disable-debug --with-libiconv --with-boost-python="boost_python36" CXXFLAGS=-std=c++17 --with-boost-libdir="/usr/local/src/boost/stage/lib/"
make -j$(nproc)
```

Build fails with the following error message

**Error Highlight - Part 1**
```
root@4efe6c69cdc4:/usr/local/src/libtorrent-rasterbar-RC_1_2# make -j$(nproc)
Making all in include/libtorrent
make[1]: Entering directory '/usr/local/src/libtorrent-rasterbar-RC_1_2/include/libtorrent'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/usr/local/src/libtorrent-rasterbar-RC_1_2/include/libtorrent'
Making all in src
make[1]: Entering directory '/usr/local/src/libtorrent-rasterbar-RC_1_2/src'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/usr/local/src/libtorrent-rasterbar-RC_1_2/src'
Making all in examples
make[1]: Entering directory '/usr/local/src/libtorrent-rasterbar-RC_1_2/examples'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/usr/local/src/libtorrent-rasterbar-RC_1_2/examples'
Making all in test
make[1]: Entering directory '/usr/local/src/libtorrent-rasterbar-RC_1_2/test'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/usr/local/src/libtorrent-rasterbar-RC_1_2/test'
Making all in bindings
make[1]: Entering directory '/usr/local/src/libtorrent-rasterbar-RC_1_2/bindings'
Making all in python
make[2]: Entering directory '/usr/local/src/libtorrent-rasterbar-RC_1_2/bindings/python'
/usr/bin/python3.6 ./setup.py build
running build
running build_ext
project-config.jam contents:
import feature ;
feature.feature libtorrent-python : on ;
using python : 3.6 : "/usr/bin/python3.6" : "/usr/include/python3.6m" "/usr/include/python3.6m" : : <libtorrent-python>on : ".cpython-3                                     6m-x86_64-linux-gnu" ;

b2 boost-link=shared libtorrent-link=prebuilt deprecated-functions=on variant=release address-model=64 python=3.6 libtorrent-python=on                                      python-install-path=/usr/local/src/libtorrent-rasterbar-RC_1_2/bindings/python/build/lib.linux-x86_64-3.6 install_module linkflags=-L/u                                     sr/local/src/libtorrent-rasterbar-RC_1_2/bindings/python/../../src/.libs linkflags=-L/usr/local/src//boost/stage/lib/ linkflags=-L/usr/                                     local/src//boost/stage/lib/ linkflags=-L/usr/local/lib
 cxxflags=-std=c++17
CXXFLAGS =
LDFLAGS =
OS = LINUX
building boost from source directory:  /usr/local/src/boost
CXXFLAGS =
LDFLAGS =
warning: No toolsets are configured.
warning: Configuring default toolset "gcc".
warning: If the default is wrong, your build may not work correctly.
warning: Use the "toolset=xxxxx" option to override our guess.
warning: For more configuration options, please consult
warning: http://boost.org/boost-build2/doc/html/bbv2/advanced/configuration.html
Performing configuration checks

    - default address-model    : 64-bit [1]
    - default architecture     : x86 [1]

[1] gcc-7
...patience...
...patience...
...patience...
...found 4984 targets...
...updating 63 targets...
gcc.compile.c++ /usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/long.o
gcc.compile.c++ /usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/tuple.o
gcc.compile.c++ /usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/list.o
gcc.compile.c++ /usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/dict.o
gcc.compile.c++ /usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/converter/from_python.o
gcc.compile.c++ /usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/converter/registry.o
gcc.compile.c++ /usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/converter/type_id.o
gcc.compile.c++ /usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/slice.o
gcc.compile.c++ /usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/str.o
gcc.compile.c++ /usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/object/enum.o
gcc.compile.c++ /usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/object/life_support.o
gcc.compile.c++ /usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/object/class.o
gcc.compile.c++ /usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/object/function.o
In file included from /usr/local/src/boost/libs/python/src/object/function.cpp:24:0:
/usr/local/src/boost/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the g                                     lobal namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLAC                                     EHOLDERS to retain the current behavior.
 )
 ^
gcc.compile.c++ /usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/errors.o
gcc.compile.c++ /usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/object/pickle_support.o
gcc.compile.c++ /usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/converter/builtin_converter                                     s.o
gcc.compile.c++ /usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/object/inheritance.o
In file included from /usr/local/src/boost/boost/graph/adjacency_iterator.hpp:13:0,
                 from /usr/local/src/boost/boost/graph/detail/adjacency_list.hpp:37,
                 from /usr/local/src/boost/boost/graph/adjacency_list.hpp:255,
                 from /usr/local/src/boost/libs/python/src/object/inheritance.cpp:11:
/usr/local/src/boost/boost/detail/iterator.hpp:13:37: note: #pragma message: This header is deprecated. Use <iterator> instead.
 BOOST_HEADER_DEPRECATED("<iterator>")
                                     ^
In file included from /usr/local/src/boost/libs/python/src/object/inheritance.cpp:14:0:
/usr/local/src/boost/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the g                                     lobal namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLAC                                     EHOLDERS to retain the current behavior.
 )
 ^
gcc.compile.c++ /usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/module.o
gcc.compile.c++ /usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/converter/arg_to_python_bas                                     e.o
gcc.compile.c++ /usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/object/iterator.o
In file included from /usr/local/src/boost/libs/python/src/object/iterator.cpp:8:0:
/usr/local/src/boost/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the g                                     lobal namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLAC                                     EHOLDERS to retain the current behavior.
 )
 ^
gcc.compile.c++ /usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/object/stl_iterator.o
gcc.compile.c++ /usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/object_protocol.o
gcc.compile.c++ /usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/object_operators.o
gcc.compile.c++ /usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/wrapper.o
gcc.compile.c++ /usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/import.o
gcc.compile.c++ bin/gcc-7/release/address-model-64/lt-visibility-hidden/python-3.6/src/module.o
gcc.compile.c++ /usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/exec.o
gcc.compile.c++ /usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/object/function_doc_signatu                                     re.o
gcc.link.dll /usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/libboost_python36.so.1.76.0
/bin/sh: 3: -L/usr/local/src//boost/stage/lib: not found

    "g++"    -o "/usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/libboost_python36.so.1.76.                                     0" -Wl,-h -Wl,libboost_python36.so.1.76.0 -shared -Wl,--start-group "/usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-vis                                     ibility-hidden/python-3.6/list.o" "/usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/long.o"                                      "/usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/dict.o" "/usr/local/src/boost/bin.v2/libs/                                     python/build/gcc-7/release/lt-visibility-hidden/python-3.6/tuple.o" "/usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-vis                                     ibility-hidden/python-3.6/str.o" "/usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/slice.o"                                      "/usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/converter/from_python.o" "/usr/local/src/b                                     oost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/converter/registry.o" "/usr/local/src/boost/bin.v2/libs/pyt                                     hon/build/gcc-7/release/lt-visibility-hidden/python-3.6/converter/type_id.o" "/usr/local/src/boost/bin.v2/libs/python/build/gcc-7/relea                                     se/lt-visibility-hidden/python-3.6/object/enum.o" "/usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/pyt                                     hon-3.6/object/class.o" "/usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/object/function.o"                                      "/usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/object/inheritance.o" "/usr/local/src/boo                                     st/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/object/life_support.o" "/usr/local/src/boost/bin.v2/libs/pyth                                     on/build/gcc-7/release/lt-visibility-hidden/python-3.6/object/pickle_support.o" "/usr/local/src/boost/bin.v2/libs/python/build/gcc-7/re                                     lease/lt-visibility-hidden/python-3.6/errors.o" "/usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/pytho                                     n-3.6/module.o" "/usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/converter/builtin_converte                                     rs.o" "/usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/converter/arg_to_python_base.o" "/us                                     r/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/object/iterator.o" "/usr/local/src/boost/bin.v                                     2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/object/stl_iterator.o" "/usr/local/src/boost/bin.v2/libs/python/build                                     /gcc-7/release/lt-visibility-hidden/python-3.6/object_protocol.o" "/usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visib                                     ility-hidden/python-3.6/object_operators.o" "/usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.                                     6/wrapper.o" "/usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/import.o" "/usr/local/src/boo                                     st/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/exec.o" "/usr/local/src/boost/bin.v2/libs/python/build/gcc-7/                                     release/lt-visibility-hidden/python-3.6/object/function_doc_signature.o"  -Wl,-Bstatic  -Wl,-Bdynamic -ldl -lpthread -lutil -Wl,--end-g                                     roup -fPIC -m64 -L/usr/local/lib
 -L/usr/local/src//boost/stage/lib -L/usr/local/src/libtorrent-rasterbar-RC_1_2/bindings/python/../../src/.libs

...failed gcc.link.dll /usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/libboost_python36.so                                     .1.76.0...
...removing /usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/libboost_python36.so.1.76.0
gcc.compile.c++ bin/gcc-7/release/address-model-64/lt-visibility-hidden/python-3.6/src/sha1_hash.o
In file included from /usr/local/src/boost/boost/python/exception_translator.hpp:10:0,
                 from /usr/local/src/boost/boost/python.hpp:28,
                 from src/boost_python.hpp:10,
                 from src/sha1_hash.cpp:5:
/usr/local/src/boost/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the g                                     lobal namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLAC                                     EHOLDERS to retain the current behavior.
 )
 ^
gcc.compile.c++ bin/gcc-7/release/address-model-64/lt-visibility-hidden/python-3.6/src/fingerprint.o
In file included from /usr/local/src/boost/boost/python/exception_translator.hpp:10:0,
                 from /usr/local/src/boost/boost/python.hpp:28,
                 from src/boost_python.hpp:10,
                 from src/fingerprint.cpp:5:
/usr/local/src/boost/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the g                                     lobal namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLAC                                     EHOLDERS to retain the current behavior.
 )
 ^
gcc.compile.c++ bin/gcc-7/release/address-model-64/lt-visibility-hidden/python-3.6/src/converters.o
In file included from /usr/local/src/boost/boost/python/exception_translator.hpp:10:0,
                 from /usr/local/src/boost/boost/python.hpp:28,
                 from src/boost_python.hpp:10,
                 from src/converters.cpp:5:
/usr/local/src/boost/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the g                                     lobal namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLAC                                     EHOLDERS to retain the current behavior.
 )
 ^
gcc.compile.c++ bin/gcc-7/release/address-model-64/lt-visibility-hidden/python-3.6/src/utility.o
In file included from /usr/local/src/boost/boost/python/exception_translator.hpp:10:0,
                 from /usr/local/src/boost/boost/python.hpp:28,
                 from src/boost_python.hpp:10,
                 from src/utility.cpp:5:
/usr/local/src/boost/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the g                                     lobal namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLAC                                     EHOLDERS to retain the current behavior.
 )
 ^
gcc.compile.c++ bin/gcc-7/release/address-model-64/lt-visibility-hidden/python-3.6/src/create_torrent.o
In file included from /usr/local/src/boost/boost/python/exception_translator.hpp:10:0,
                 from /usr/local/src/boost/boost/python.hpp:28,
                 from src/boost_python.hpp:10,
                 from src/create_torrent.cpp:5:
/usr/local/src/boost/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the g                                     lobal namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLAC                                     EHOLDERS to retain the current behavior.
 )
 ^
gcc.compile.c++ bin/gcc-7/release/address-model-64/lt-visibility-hidden/python-3.6/src/string.o
In file included from /usr/local/src/boost/boost/python/exception_translator.hpp:10:0,
                 from /usr/local/src/boost/boost/python.hpp:28,
                 from src/boost_python.hpp:10,
                 from src/string.cpp:5:
/usr/local/src/boost/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the g                                     lobal namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLAC                                     EHOLDERS to retain the current behavior.
 )
 ^
gcc.compile.c++ bin/gcc-7/release/address-model-64/lt-visibility-hidden/python-3.6/src/entry.o
In file included from /usr/local/src/boost/boost/python/exception_translator.hpp:10:0,
                 from /usr/local/src/boost/boost/python.hpp:28,
                 from src/boost_python.hpp:10,
                 from src/entry.cpp:5:
/usr/local/src/boost/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the g                                     lobal namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLAC                                     EHOLDERS to retain the current behavior.
 )
 ^
gcc.compile.c++ bin/gcc-7/release/address-model-64/lt-visibility-hidden/python-3.6/src/torrent_info.o
In file included from /usr/local/src/boost/boost/python/exception_translator.hpp:10:0,
                 from /usr/local/src/boost/boost/python.hpp:28,
                 from src/boost_python.hpp:10,
                 from src/torrent_info.cpp:7:
/usr/local/src/boost/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the g                                     lobal namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLAC                                     EHOLDERS to retain the current behavior.
 )
 ^
gcc.compile.c++ bin/gcc-7/release/address-model-64/lt-visibility-hidden/python-3.6/src/torrent_status.o
In file included from /usr/local/src/boost/boost/python/exception_translator.hpp:10:0,
                 from /usr/local/src/boost/boost/python.hpp:28,
                 from src/boost_python.hpp:10,
                 from src/torrent_status.cpp:5:
/usr/local/src/boost/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
 )
 ^
gcc.compile.c++ bin/gcc-7/release/address-model-64/lt-visibility-hidden/python-3.6/src/session.o
In file included from /usr/local/src/boost/boost/python/exception_translator.hpp:10:0,
                 from /usr/local/src/boost/boost/python.hpp:28,
                 from src/boost_python.hpp:10,
                 from src/session.cpp:5:
/usr/local/src/boost/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
 )
 ^
gcc.compile.c++ bin/gcc-7/release/address-model-64/lt-visibility-hidden/python-3.6/src/session_settings.o
In file included from /usr/local/src/boost/boost/python/exception_translator.hpp:10:0,
                 from /usr/local/src/boost/boost/python.hpp:28,
                 from src/boost_python.hpp:10,
                 from src/session_settings.cpp:5:
/usr/local/src/boost/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
 )
 ^
gcc.compile.c++ bin/gcc-7/release/address-model-64/lt-visibility-hidden/python-3.6/src/torrent_handle.o
In file included from /usr/local/src/boost/boost/python/exception_translator.hpp:10:0,
                 from /usr/local/src/boost/boost/python.hpp:28,
                 from src/boost_python.hpp:10,
                 from src/torrent_handle.cpp:5:
/usr/local/src/boost/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
 )
 ^
gcc.compile.c++ bin/gcc-7/release/address-model-64/lt-visibility-hidden/python-3.6/src/version.o
In file included from /usr/local/src/boost/boost/python/exception_translator.hpp:10:0,
                 from /usr/local/src/boost/boost/python.hpp:28,
                 from src/boost_python.hpp:10,
                 from src/version.cpp:5:
/usr/local/src/boost/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
 )
 ^
gcc.compile.c++ bin/gcc-7/release/address-model-64/lt-visibility-hidden/python-3.6/src/datetime.o
In file included from /usr/local/src/boost/boost/python/exception_translator.hpp:10:0,
                 from /usr/local/src/boost/boost/python.hpp:28,
                 from src/boost_python.hpp:10,
                 from src/datetime.cpp:5:
/usr/local/src/boost/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
 )
 ^
gcc.compile.c++ bin/gcc-7/release/address-model-64/lt-visibility-hidden/python-3.6/src/ip_filter.o
In file included from /usr/local/src/boost/boost/python/exception_translator.hpp:10:0,
                 from /usr/local/src/boost/boost/python.hpp:28,
                 from src/boost_python.hpp:10,
                 from src/ip_filter.cpp:5:
/usr/local/src/boost/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
 )
 ^
gcc.compile.c++ bin/gcc-7/release/address-model-64/lt-visibility-hidden/python-3.6/src/peer_info.o
In file included from /usr/local/src/boost/boost/python/exception_translator.hpp:10:0,
                 from /usr/local/src/boost/boost/python.hpp:28,
                 from src/boost_python.hpp:10,
                 from src/peer_info.cpp:5:
/usr/local/src/boost/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
 )
 ^
gcc.compile.c++ bin/gcc-7/release/address-model-64/lt-visibility-hidden/python-3.6/src/magnet_uri.o
In file included from /usr/local/src/boost/boost/python/exception_translator.hpp:10:0,
                 from /usr/local/src/boost/boost/python.hpp:28,
                 from src/boost_python.hpp:10,
                 from src/magnet_uri.cpp:5:
/usr/local/src/boost/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
 )
 ^
gcc.compile.c++ bin/gcc-7/release/address-model-64/lt-visibility-hidden/python-3.6/src/error_code.o
In file included from /usr/local/src/boost/boost/python/exception_translator.hpp:10:0,
                 from /usr/local/src/boost/boost/python.hpp:28,
                 from src/boost_python.hpp:10,
                 from src/error_code.cpp:33:
/usr/local/src/boost/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
 )
 ^
gcc.compile.c++ bin/gcc-7/release/address-model-64/lt-visibility-hidden/python-3.6/src/alert.o
In file included from /usr/local/src/boost/boost/python/exception_translator.hpp:10:0,
                 from /usr/local/src/boost/boost/python.hpp:28,
                 from src/boost_python.hpp:10,
                 from src/alert.cpp:5:
/usr/local/src/boost/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
 )
 ^
...skipped <pbin/gcc-7/release/address-model-64/lt-visibility-hidden/python-3.6>libtorrent.cpython-36m-x86_64-linux-gnu.so for lack of <p/usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6>libboost_python36.so.1.76.0...
...skipped <p/usr/local/src/libtorrent-rasterbar-RC_1_2/bindings/python/build/lib.linux-x86_64-3.6>libtorrent.cpython-36m-x86_64-linux-gnu.so for lack of <pbin/gcc-7/release/address-model-64/lt-visibility-hidden/python-3.6>libtorrent.cpython-36m-x86_64-linux-gnu.so...
...failed updating 1 target...
...skipped 2 targets...
...updated 60 targets...
Traceback (most recent call last):
  File "./setup.py", line 463, in <module>
    distclass=B2Distribution,
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "./setup.py", line 348, in run
    self._build_extension_with_b2()
  File "./setup.py", line 367, in _build_extension_with_b2
    subprocess.run(command, cwd=python_binding_dir, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['b2', 'boost-link=shared', 'libtorrent-link=prebuilt', 'deprecated-functions=on', 'variant=release', 'address-model=64', 'python=3.6', 'libtorrent-python=on', 'python-install-path=/usr/local/src/libtorrent-rasterbar-RC_1_2/bindings/python/build/lib.linux-x86_64-3.6', 'install_module', 'linkflags=-L/usr/local/src/libtorrent-rasterbar-RC_1_2/bindings/python/../../src/.libs', 'linkflags=-L/usr/local/src//boost/stage/lib/', 'linkflags=-L/usr/local/src//boost/stage/lib/', 'linkflags=-L/usr/local/lib\n', 'cxxflags=-std=c++17']' returned non-zero exit status 1.
Makefile:538: recipe for target 'all-local' failed
make[2]: *** [all-local] Error 1
make[2]: Leaving directory '/usr/local/src/libtorrent-rasterbar-RC_1_2/bindings/python'
Makefile:407: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/local/src/libtorrent-rasterbar-RC_1_2/bindings'
Makefile:660: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

```

Since 1.2.12 the python binding build process became very error-prone/hard. Any help on this issue would be appreciated.

**Comment by AllSeeingEyeTolledEweSew** [comment]
```
gcc.link.dll /usr/local/src/boost/bin.v2/libs/python/build/gcc-7/release/lt-visibility-hidden/python-3.6/libboost_python36.so.1.76.0
/bin/sh: 3: -L/usr/local/src//boost/stage/lib: not found
```

looks like it's actually trying to build boost.python inline, and failing. Seems like an issue with the boost setup.

But, it may have been triggered by changes in `setup.py`.

@arvidn looks like the autotools path in `RC_1_2` calls `setup.py`. IIRC the old `setup.py` *itself* invoked more autotools by default, so maybe my refactor broke this path. Thoughts?

**Comment by AllSeeingEyeTolledEweSew** [comment]
@SSoft7 one root cause of brokenness here is that libtorrent is deprecating its use of autotools. It *should* still work in `RC_1_2` but maybe we didn't test it enough.

You may get better support if you instead build with `b2` directly, or invoke `setup.py` which bridges distutils and `b2`

**Comment by arvidn** [comment]
You have a lot of spaces in your output that obfuscates the issue. This seems to be the failure:
```
/bin/sh: 3: -L/usr/local/src//boost/stage/lib: not found
```
