### ISSUE TITLE
libtorrent.cpython-38-x86_64-linux-gnu.so missing

### ISSUE THREAD

**Issue by dylangerdaly** [arvidn/libtorrent#6417]
**Please provide the following information**

libtorrent version (or branch): v1.2.13

platform/architecture: x86_64

Attempting to compile python-bindings results in the following error

```
root@4c2bcc66ff21:/mnt/media/libtorrent/bindings/python# python3 setup.py build_ext --b2-args="libtorrent-link=static" install --user --prefix=
running build_ext
project-config.jam contents:
import feature ;
feature.feature libtorrent-python : on ;
using python : 3.8 : "/usr/bin/python3" : "/usr/include/python3.8" "/usr/include/python3.8" : : <libtorrent-python>on : ".cpython-38-x86_64-linux-gnu" ;

b2 libtorrent-link=static boost-link=shared deprecated-functions=on variant=release address-model=64 python=3.8 libtorrent-python=on python-install-path=/mnt/media/libtorrent/bindings/python/build/lib.linux-x86_64-3.8 install_module linkflags=-L/mnt/media/libtorrent/bindings/python/../../src/.libs linkflags=-L/usr/lib/x86_64-linux-gnu linkflags=-L/usr/lib/x86_64-linux-gnu linkflags=-L/usr/lib

<string>:1: DeprecationWarning: SO is deprecated, use EXT_SUFFIX
CXXFLAGS =
LDFLAGS =
OS = LINUX
CXXFLAGS =
LDFLAGS =
warning: No toolsets are configured.
warning: Configuring default toolset "gcc".
warning: If the default is wrong, your build may not work correctly.
warning: Use the "toolset=xxxxx" option to override our guess.
warning: For more configuration options, please consult
warning: http://boost.org/boost-build2/doc/html/bbv2/advanced/configuration.html
...patience...
...found 1498 targets...
...updating 24 targets...
gcc.compile.c++ bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/module.o
gcc.compile.c++ bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/fingerprint.o
gcc.compile.c++ bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/sha1_hash.o
gcc.compile.c++ bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/utility.o
gcc.compile.c++ bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/converters.o
gcc.compile.c++ bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/create_torrent.o
gcc.compile.c++ bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/string.o
gcc.compile.c++ bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/entry.o
gcc.compile.c++ bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/torrent_info.o
gcc.compile.c++ bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/torrent_status.o
gcc.compile.c++ bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/version.o
gcc.compile.c++ bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/session.o
gcc.compile.c++ bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/torrent_handle.o
gcc.compile.c++ bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/session_settings.o
gcc.compile.c++ bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/datetime.o
gcc.compile.c++ bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/ip_filter.o
gcc.compile.c++ bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/peer_info.o
gcc.compile.c++ bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/magnet_uri.o
gcc.compile.c++ bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/error_code.o
gcc.compile.c++ bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/alert.o
gcc.link.dll bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/libtorrent.cpython-38-x86_64-linux-gnu.so
/bin/sh: 3: -L/usr/lib/x86_64-linux-gnu: not found

    "g++" -L"/opt/homebrew/lib" -L"/usr/local/opt/boost/lib"   -o "bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/libtorrent.cpython-38-x86_64-linux-gnu.so" -Wl,-h -Wl,libtorrent.cpython-38-x86_64-linux-gnu.so -shared -Wl,--start-group "bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/module.o" "bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/sha1_hash.o" "bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/converters.o" "bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/create_torrent.o" "bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/fingerprint.o" "bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/utility.o" "bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/session.o" "bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/entry.o" "bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/torrent_info.o" "bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/string.o" "bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/torrent_handle.o" "bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/torrent_status.o" "bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/session_settings.o" "bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/version.o" "bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/alert.o" "bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/datetime.o" "bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/peer_info.o" "bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/ip_filter.o" "bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/magnet_uri.o" "bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/src/error_code.o" "../../bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/link-static/lt-visibility-hidden/threading-multi/libtorrent-rasterbar.a"  -Wl,-Bstatic  -Wl,-Bdynamic -ldl -lpthread -lutil -lboost_python38 -lboost_system -Wl,--end-group -fPIC -L/mnt/media/libtorrent/bindings/python/../../src/.libs -L/usr/lib
 -L/usr/lib/x86_64-linux-gnu -Wl,-Bsymbolic

...failed gcc.link.dll bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/libtorrent.cpython-38-x86_64-linux-gnu.so...
...removing bin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/libtorrent.cpython-38-x86_64-linux-gnu.so
...skipped <p/mnt/media/libtorrent/bindings/python/build/lib.linux-x86_64-3.8>libtorrent.cpython-38-x86_64-linux-gnu.so for lack of <pbin/gcc-9/release/address-model-64/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8>libtorrent.cpython-38-x86_64-linux-gnu.so...
...failed updating 1 target...
...skipped 1 target...
...updated 22 targets...
Traceback (most recent call last):
  File "setup.py", line 450, in <module>
    setuptools.setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 348, in run
    self._build_extension_with_b2()
  File "setup.py", line 367, in _build_extension_with_b2
    subprocess.run(command, cwd=python_binding_dir, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['b2', 'libtorrent-link=static', 'boost-link=shared', 'deprecated-functions=on', 'variant=release', 'address-model=64', 'python=3.8', 'libtorrent-python=on', 'python-install-path=/mnt/media/libtorrent/bindings/python/build/lib.linux-x86_64-3.8', 'install_module', 'linkflags=-L/mnt/media/libtorrent/bindings/python/../../src/.libs', 'linkflags=-L/usr/lib/x86_64-linux-gnu', 'linkflags=-L/usr/lib/x86_64-linux-gnu', 'linkflags=-L/usr/lib\n']' returned non-zero exit status 1.
```

**Comment by arvidn** [comment]
`libtorrent.cpython-38-x86_64-linux-gnu.so` is the output file from the linker. I don't think that's the file that can't be found. It looks like the linker is treating this as a file, and then not finding it:
```
/bin/sh: 3: -L/usr/lib/x86_64-linux-gnu: not found
```

I don't see what's wrong with that. Presumably a `-L` argument may point to a directory that doesn't exist. that flag comes from the b2 command line option `linkflags=`.

As far as I can tell, that's populated by the file `link_flags` in the current working directory. Do you have such file? If so, try deleting it. It's just there for backwards compatibility.

**Comment by dylangerdaly** [comment]
Thank you, I deleted the file and it allowed me to compile it statically, I've just found out the python wheel that's compiled is all that's needed for deluge 👍  makes my podman container much smoother

Thank you
