### ISSUE TITLE
python3 setup.py build failed

### ISSUE THREAD

**Issue by pluschen-stack** [arvidn/libtorrent#6833]
**Please provide the following information**

libtorrent version (or branch):RC_2_0

platform/architecture:wsl ubuntu20.04

compiler and compiler version:

```
~/libtorrent$ b2 --version
B2 4.8-git
```

```
~/ibtorrent$ gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
```

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
i run 
```libtorrent$ python3 setup.py build | grep 'failed'```
here is the result 
```
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/alert.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/alert_manager.o...
...failed gcc.compile.c++ bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.8/src/magnet_uri.o...
...failed gcc.compile.c++ bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.8/src/converters.o...
...failed gcc.compile.c++ bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.8/src/session.o...
...failed gcc.compile.c++ bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.8/src/create_torrent.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/choker.o...
...failed gcc.compile.c++ bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.8/src/torrent_info.o...
...failed gcc.compile.c++ bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.8/src/error_code.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/file_storage.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/create_torrent.o...
...failed gcc.compile.c++ bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.8/src/alert.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/hasher.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/hash_picker.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/http_connection.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/merkle.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/merkle_tree.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/ip_voter.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/listen_socket_handle.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/peer_connection.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/bt_peer_connection.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/web_connection_base.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/random.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/web_peer_connection.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/http_seed_connection.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/peer_connection_handle.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/instantiate_connection.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/piece_picker.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/peer_list.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/read_resume_data.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/session_impl.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/write_resume_data.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/session_params.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/session.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/session_handle.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/socket_io.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/session_call.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/settings_pack.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/socket_type.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/torrent.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/torrent_info.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/torrent_handle.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/torrent_peer.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/tracker_manager.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/http_tracker_connection.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/udp_tracker_connection.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/udp_socket.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/upnp.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/part_file.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/utp_stream.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/utp_socket_manager.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/enum_net.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/peer_class.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/request_blocks.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/mmap_disk_io.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/mmap_storage.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/file_progress.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/posix_disk_io.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/posix_part_file.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/ssl.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/posix_storage.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/smart_ban.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/ed25519/add_scalar.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/ed25519/keypair.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/ed25519/sign.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/ut_pex.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/ed25519/hasher512.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/ut_metadata.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/ed25519/verify.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/kademlia/item.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/kademlia/dht_tracker.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/kademlia/find_data.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/kademlia/dos_blocker.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/kademlia/get_peers.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/kademlia/get_item.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/kademlia/node_id.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/kademlia/node.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/kademlia/put_data.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/kademlia/refresh.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/kademlia/routing_table.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/kademlia/rpc_manager.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/kademlia/traversal_algorithm.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/kademlia/sample_infohashes.o...
...failed gcc.compile.c++ ../../bin/gcc-9/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/src/pe_crypto.o...
...failed updating 84 targets...
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    import distutils.util
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "setup.py", line 449, in <module>
    setuptools.setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 328, in run
    self._build_extension_with_b2()
  File "setup.py", line 347, in _build_extension_with_b2
    subprocess.run(command, cwd=python_binding_dir, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['b2', 'boost-link=static', 'libtorrent-link=static', 'crypto=openssl', 'deprecated-functions=on', 'variant=release', 'address-model=64', 'python=3.8', 'libtorrent-python=on', 'python-install-path=/home/p1uschen/bittorrentLab/libtorrent/bindings/python/build/lib.linux-x86_64-3.8', 'install_module', '--project-config=/tmp/tmpw91n804i']' returned non-zero exit status 1.
```
how can i do for this?

**Comment by pluschen-stack** [comment]
i have found that i am lack of some lib
and do this
``` 
$ sudo apt-get install libssl-dev
```
```
$ sudo ln -s /usr/lib/x86_64-linux-gnu/libboost_python38.so.1.71.0 /usr/lib/x86_64-linux-gnu/libboost_python38.so
```
i solve the problem

**Comment by pluschen-stack** [comment]
i have solved the problem .
