### ISSUE TITLE
SIGSEGV in libtorrent::packet_pool::alloc

### ISSUE THREAD

**Issue by copsTvFan** [arvidn/libtorrent#7307]
Today my headless qBittorrent (`qbittorrent-nox`) crashed with a new stack trace. This was during normal seeding, not during startup/shutdown. I wasn't interacting with it at all.

I am running

- qBittorrent `4.4.5`
- libtorrent `1.2.18`
- platform/architecture: `Linux/x86_64`
- compiler: `gcc 11.3.1`

Traceback:

```
Thread 3 "qbittorrent-nox" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff35496c0 (LWP 2756713)]
0x00007ffff7e5b160 in libtorrent::packet_pool::alloc (this=0x7ff81ac652d5, allocate=allocate@entry=548) at /usr/src/debug/net-libs/libtorrent-rasterbar-1.2.18/libtorrent-rasterbar-1.2.18/include/libtorrent/packet_pool.hpp:209
209                             if (allocate <= m_syn_slab.allocate_size) { return m_syn_slab.alloc(); }
(gdb) bt
#0  0x00007ffff7e5b160 in libtorrent::packet_pool::alloc (this=0x7ff81ac652d5, allocate=allocate@entry=548)
    at /usr/src/debug/net-libs/libtorrent-rasterbar-1.2.18/libtorrent-rasterbar-1.2.18/include/libtorrent/packet_pool.hpp:209
#1  0x00007ffff7e586fe in libtorrent::packet_pool::acquire (allocate=548, this=<optimized out>)
    at /usr/src/debug/net-libs/libtorrent-rasterbar-1.2.18/libtorrent-rasterbar-1.2.18/include/libtorrent/packet_pool.hpp:180
#2  libtorrent::utp_socket_manager::acquire_packet (allocate=548, this=<optimized out>)
    at /usr/src/debug/net-libs/libtorrent-rasterbar-1.2.18/libtorrent-rasterbar-1.2.18/include/libtorrent/utp_socket_manager.hpp:133
#3  libtorrent::utp_socket_impl::acquire_packet (allocate=548, this=0x7fffe6375bd0) at /usr/src/debug/net-libs/libtorrent-rasterbar-1.2.18/libtorrent-rasterbar-1.2.18/src/utp_stream.cpp:288
#4  libtorrent::utp_socket_impl::send_pkt (this=0x7fffe6375bd0, flags=<optimized out>) at /usr/src/debug/net-libs/libtorrent-rasterbar-1.2.18/libtorrent-rasterbar-1.2.18/src/utp_stream.cpp:1907
#5  0x00007ffff7e53498 in libtorrent::utp_socket_manager::incoming_packet (this=0x555555ce4168, socket=std::weak_ptr<libtorrent::utp_socket_interface> (use count 1, weak count 11516) = {...}, ep=..., p=...)
    at /usr/src/debug/net-libs/libtorrent-rasterbar-1.2.18/libtorrent-rasterbar-1.2.18/src/utp_socket_manager.cpp:171
#6  0x00007ffff7d6556b in libtorrent::aux::session_impl::on_udp_packet (this=0x555555ce2250, socket=std::weak_ptr<libtorrent::aux::session_udp_socket> (use count 2, weak count 2) = {...},
    ls=std::weak_ptr<libtorrent::aux::listen_socket_t> (use count 1, weak count 11516) = {...}, ssl=<optimized out>, ec=...)
    at /usr/src/debug/net-libs/libtorrent-rasterbar-1.2.18/libtorrent-rasterbar-1.2.18/src/session_impl.cpp:2460
#7  0x00007ffff7d7d25d in std::__invoke_impl<void, void (libtorrent::aux::session_impl::* const&)(std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, boost::system::error_code const&), libtorrent::aux::session_impl* const&, std::weak_ptr<libtorrent::aux::session_udp_socket> const&, std::weak_ptr<libtorrent::aux::listen_socket_t> const&, libtorrent::aux::transport const&, boost::system::error_code const&> (
    __f=@0x7ffff3547730: (void (libtorrent::aux::session_impl::*)(libtorrent::aux::session_impl * const, std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, const boost::system::error_code &)) 0x7ffff7d65130 <libtorrent::aux::session_impl::on_udp_packet(std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, boost::system::error_code const&)>, __t=@0x7ffff3547768: 0x555555ce2250,
    __f=@0x7ffff3547730: (void (libtorrent::aux::session_impl::*)(libtorrent::aux::session_impl * const, std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, const boost::system::error_code &)) 0x7ffff7d65130 <libtorrent::aux::session_impl::on_udp_packet(std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, boost::system::error_code const&)>, __t=@0x7ffff3547768: 0x555555ce2250) at /usr/lib/gcc/x86_64-pc-linux-gnu/11/include/g++-v11/bits/invoke.h:74
#8  std::__invoke<void (libtorrent::aux::session_impl::* const&)(std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, boost::system::error_code const&), libtorrent::aux::session_impl* const&, std::weak_ptr<libtorrent::aux::session_udp_socket> const&, std::weak_ptr<libtorrent::aux::listen_socket_t> const&, libtorrent::aux::transport const&, boost::system::error_code const&> (
    __fn=@0x7ffff3547730: (void (libtorrent::aux::session_impl::*)(libtorrent::aux::session_impl * const, std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, const boost::system::error_code &)) 0x7ffff7d65130 <libtorrent::aux::session_impl::on_udp_packet(std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, boost::system::error_code const&)>) at /usr/lib/gcc/x86_64-pc-linux-gnu/11/include/g++-v11/bits/invoke.h:96
#9  std::_Bind<void (libtorrent::aux::session_impl::*(libtorrent::aux::session_impl*, std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, std::_Placeholder<1>))(std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, boost::system::error_code const&)>::__call_c<void, boost::system::error_code const&, unsigned long const&, 0ul, 1ul, 2ul, 3ul, 4ul>(std::tuple<boost::system::error_code const&, unsigned long const&>&&, std::_Index_tuple<0ul, 1ul, 2ul, 3ul, 4ul>) const (__args=...,
    this=0x7ffff3547730) at /usr/lib/gcc/x86_64-pc-linux-gnu/11/include/g++-v11/functional:431
#10 std::_Bind<void (libtorrent::aux::session_impl::*(libtorrent::aux::session_impl*, std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, std::_Placeholder<1>))(std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, boost::system::error_code const&)>::operator()<boost::system::error_code const&, unsigned long const&, void>(boost::system::error_code const&, unsigned long const&) const (this=0x7ffff3547730) at /usr/lib/gcc/x86_64-pc-linux-gnu/11/include/g++-v11/functional:515
#11 libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::aux::session_impl::*(libtorrent::aux::session_impl*, std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, std::_Placeholder<1>))(std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, boost::system::error_code const&)>, 432ul>::operator()<boost::system::error_code const&, unsigned long const&>(boost::system::error_code const&, unsigned long const&) const (this=0x7ffff3547730)
    at /usr/src/debug/net-libs/libtorrent-rasterbar-1.2.18/libtorrent-rasterbar-1.2.18/include/libtorrent/aux_/allocating_handler.hpp:101
#12 0x00007ffff7d7d5f0 in boost::asio::detail::binder2<libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::aux::session_impl::*(libtorrent::aux::session_impl*, std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, std::_Placeholder<1>))(std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, boost::system::error_code const&)>, 432ul>, boost::system::error_code, unsigned long>::operator()() (this=0x7ffff3547730) at /usr/include/boost/asio/detail/bind_handler.hpp:287
#13 boost::asio::asio_handler_invoke<boost::asio::detail::binder2<libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::aux::session_impl::*(libtorrent::aux::session_impl*, std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, std::_Placeholder<1>))(std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, boost::system::error_code const&)>, 432ul>, boost::system::error_code, unsigned long> >(boost::asio::detail::binder2<libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::aux::session_impl::*(libtorrent::aux::session_impl*, std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, std::_Placeholder<1>))(std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, boost::system::error_code const&)>, 432ul>, boost::system::error_code, unsigned long>&, ...) (function=...) at /usr/include/boost/asio/handler_invoke_hook.hpp:88
#14 boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::binder2<libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::aux::session_impl::*(libtorrent::aux::session_impl*, std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, std::_Placeholder<1>))(std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, boost::system::error_code const&)>, 432ul>, boost::system::error_code, unsigned long>, libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::aux::session_impl::*(libtorrent::aux::session_impl*, std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, std::_Placeholder<1>))(std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, boost::system::error_code const&)>, 432ul> >(boost::asio::detail::binder2<libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::aux::session_impl::*(libtorrent::aux::session_impl*, std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, std::_Placeholder<1>))(std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, boost::system::error_code const&)>, 432ul>, boost::system::error_code, unsigned long>&, libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::aux::session_impl::*(libtorrent::aux::session_impl*, std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, std::_Placeholder<1>))(std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, boost::system::error_code const&)>, 432ul>&) (context=..., function=...) at /usr/include/boost/asio/detail/handler_invoke_helpers.hpp:54
#15 boost::asio::detail::handler_work<libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::aux::session_impl::*(libtorrent::aux::session_impl*, std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, std::_Placeholder<1>))(std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, boost::system::error_code const&)>, 432ul>, boost::asio::any_io_executor, void>::complete<boost::asio::detail::binder2<libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::aux::session_impl::*(libtorrent::aux::session_impl*, std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, std::_Placeholder<1>))(std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, boost::system::error_code const&)>, 432ul>, boost::system::error_code, unsigned long> >(boost::asio::detail::binder2<libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::aux::session_impl::*(libtorrent::aux::session_impl*, std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, std::_Placeholder<1>))(std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, boost::system::error_code const&)>, 432ul>, boost::system::error_code, unsigned long>&, libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::aux::session_impl::*(libtorrent::aux::session_impl*, std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, std::_Placeholder<1>))(std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, boost::system::error_code const&)>, 432ul>&) (this=0x7ffff35476f0, handler=..., function=...) at /usr/include/boost/asio/detail/handler_work.hpp:520
#16 boost::asio::detail::handler_work<libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::aux::session_impl::*(libtorrent::aux::session_impl*, std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, std::_Placeholder<1>))(std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, boost::system::error_code const&)>, 432ul>, boost::asio::any_io_executor, void>::complete<boost::asio::detail::binder2<libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::aux::session_impl::*(libtorrent::aux::session_impl*, std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, std::_Placeholder<1>))(std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, boost::system::error_code const&)>, 432ul>, boost::system::error_code, unsigned long> >(boost::asio::detail::binder2<libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::aux::session_impl::*(libtorrent::aux::session_impl*, std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, std::_Placeholder<1>))(std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, boost::system::error_code const&)>, 432ul>, boost::system::error_code, unsigned long>&, libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::aux::session_impl::*(libtorrent::aux::session_impl*, std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, std::_Placeholder<1>))(std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, boost::system::error_code const&)>, 432ul>&) (handler=..., function=..., this=0x7ffff35476f0) at /usr/include/boost/asio/detail/handler_work.hpp:513
#17 boost::asio::detail::reactive_null_buffers_op<libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::aux::session_impl::*(libtorrent::aux::session_impl*, std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, std::_Placeholder<1>))(std::weak_ptr<libtorrent::aux::session_udp_socket>, std::weak_ptr<libtorrent::aux::listen_socket_t>, libtorrent::aux::transport, boost::system::error_code const&)>, 432ul>, boost::asio::any_io_executor>::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) (owner=0x555555ce19c0, base=0x7fffe40054d0) at /usr/include/boost/asio/detail/reactive_null_buffers_op.hpp:84
#18 0x00007ffff7bf8649 in boost::asio::detail::scheduler_operation::complete (bytes_transferred=5, ec=..., owner=0x555555ce19c0, this=<optimized out>) at /usr/include/boost/asio/detail/scheduler_operation.hpp:40
#19 boost::asio::detail::scheduler::do_run_one (this=0x555555ce19c0, lock=..., this_thread=..., ec=...) at /usr/include/boost/asio/detail/impl/scheduler.ipp:492
#20 0x00007ffff7d1b351 in boost::asio::detail::scheduler::run (this=0x555555ce19c0, ec=...) at /usr/include/boost/asio/detail/impl/scheduler.ipp:210
#21 0x00007ffff7d185ee in boost::asio::io_context::run (this=<optimized out>) at /usr/include/boost/asio/impl/io_context.ipp:63
#22 operator() (__closure=<optimized out>) at /usr/src/debug/net-libs/libtorrent-rasterbar-1.2.18/libtorrent-rasterbar-1.2.18/src/session.cpp:363
#23 std::__invoke_impl<void, libtorrent::session::start(libtorrent::session_handle::session_flags_t, libtorrent::session_params&&, libtorrent::io_service*)::<lambda()> > (__f=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/11/include/g++-v11/bits/invoke.h:61
#24 std::__invoke<libtorrent::session::start(libtorrent::session_handle::session_flags_t, libtorrent::session_params&&, libtorrent::io_service*)::<lambda()> > (__fn=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/11/include/g++-v11/bits/invoke.h:96
#25 std::thread::_Invoker<std::tuple<libtorrent::session::start(libtorrent::session_handle::session_flags_t, libtorrent::session_params&&, libtorrent::io_service*)::<lambda()> > >::_M_invoke<0> (this=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/11/include/g++-v11/bits/std_thread.h:259
#26 std::thread::_Invoker<std::tuple<libtorrent::session::start(libtorrent::session_handle::session_flags_t, libtorrent::session_params&&, libtorrent::io_service*)::<lambda()> > >::operator() (this=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/11/include/g++-v11/bits/std_thread.h:266
#27 std::thread::_State_impl<std::thread::_Invoker<std::tuple<libtorrent::session::start(libtorrent::session_handle::session_flags_t, libtorrent::session_params&&, libtorrent::io_service*)::<lambda()> > > >::_M_run(void) (this=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/11/include/g++-v11/bits/std_thread.h:211
#28 0x00007ffff6fc3200 in std::execute_native_thread_routine (__p=0x555555d0a970) at /usr/src/debug/sys-devel/gcc-12.2.1_p20230121-r1/gcc-12-20230121/libstdc++-v3/src/c++11/thread.cc:82
#29 0x00007ffff6ca50bc in start_thread (arg=<optimized out>) at pthread_create.c:442
#30 0x00007ffff6d2773c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
(gdb)
```

**Comment by copsTvFan** [comment]
I am still experiencing crashes.
